import { mkdtemp, open, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, basename, dirname } from 'node:path';
import { randomUUID } from 'node:crypto';
import { spawn } from 'node:child_process';
import { promises as dns } from 'node:dns';
import { createConnection, createServer, isIP } from 'node:net';
import { makeToolResult } from '../agent/tool-envelope.mjs';
import { ProviderToolError, boundedInteger, boundedString, checkAborted, digest, exactObject, failureResult, own, result } from './provider-common.mjs';

const MAX_SESSIONS = 4;
const MAX_LINKS = 50;
const MAX_LINK_SCAN = 100;
const MAX_PAGE_TITLE = 512;
const MAX_LABEL = 256;
const MAX_URL = 2048;
const MAX_PAGE_TEXT = 16384;
const MAX_CONTROLS = 50;
const MAX_FIELD_VALUE = 4096;
const REQUEST_TIMEOUT_MS = 15000;
const CLEANUP_TIMEOUT_MS = 5000;
function absoluteLocalPath(value) { return typeof value === 'string' && value.length >= 1 && value.length <= 1024 && !/[\u0000-\u001f\u007f]/u.test(value) && (/^\//u.test(value) || /^[A-Za-z]:[\\/]/u.test(value)) && !/^\/\//u.test(value) && !/^\\\\/u.test(value); }
const PAGE_SCRIPT = `(() => { const visible = a => { const style = getComputedStyle(a); const rect = a.getBoundingClientRect(); return style.display !== 'none' && style.visibility !== 'hidden' && rect.width > 0 && rect.height > 0; }; const label = a => (a.getAttribute('aria-label') || a.innerText || a.textContent || '').replace(/\\s+/g, ' ').trim().slice(0, ${MAX_LABEL}); const links = Array.from(document.querySelectorAll('a[href]')).slice(0, ${MAX_LINK_SCAN}).map((a, index) => ({ index, href: a.href.slice(0, ${MAX_URL}), label: label(a), visible: visible(a) })).filter(a => a.visible && a.href); const controls = Array.from(document.querySelectorAll('input,textarea,select,button,[role=button]')).filter(visible).slice(0, ${MAX_CONTROLS}).map((a, index) => { const type = (a.type || (a.tagName.toLowerCase() === 'button' ? 'button' : '')).toLowerCase(); const field = ['input','textarea','select'].includes(a.tagName.toLowerCase()); return { index, kind: field ? 'field' : 'control', tag: a.tagName.toLowerCase(), type, label: label(a), disabled: !!a.disabled, readonly: !!a.readOnly, value: field && !['password','file','hidden'].includes(type) ? String(a.value || '').slice(0, ${MAX_FIELD_VALUE}) : '', form_action: a.form?.action ? a.form.action.slice(0, ${MAX_URL}) : '', href: a.href ? a.href.slice(0, ${MAX_URL}) : '' }; }); const bodyText = (document.body?.innerText || '').replace(/\\s+/g, ' ').trim().slice(0, ${MAX_PAGE_TEXT}); return { url: location.href.slice(0, ${MAX_URL}), title: (document.title || '').slice(0, ${MAX_PAGE_TITLE}), text: bodyText, links, controls }; })()`;

const schema = (properties, required = []) => ({ type: 'object', additionalProperties: false, required, properties });
const identifier = { type: 'string', minLength: 1, maxLength: 128 };
const browserSchemas = Object.freeze({
  'browser.session_start': schema({ url: { type: 'string', minLength: 1, maxLength: MAX_URL } }, ['url']),
  'browser.inspect_links': schema({ browser_session_id: identifier, limit: { type: 'integer', minimum: 1, maximum: MAX_LINKS } }, ['browser_session_id']),
  'browser.inspect_page': schema({ browser_session_id: identifier, max_text: { type: 'integer', minimum: 1, maximum: MAX_PAGE_TEXT }, max_controls: { type: 'integer', minimum: 1, maximum: MAX_CONTROLS } }, ['browser_session_id']),
  'browser.follow_link': schema({ browser_session_id: identifier, page_revision: { type: 'string', minLength: 1, maxLength: 128 }, link_id: identifier }, ['browser_session_id', 'page_revision', 'link_id']),
  'browser.fill_field': schema({ browser_session_id: identifier, page_revision: { type: 'string', minLength: 1, maxLength: 128 }, control_id: identifier, value: { type: 'string', maxLength: MAX_FIELD_VALUE } }, ['browser_session_id', 'page_revision', 'control_id', 'value']),
  'browser.activate_control': schema({ browser_session_id: identifier, page_revision: { type: 'string', minLength: 1, maxLength: 128 }, control_id: identifier }, ['browser_session_id', 'page_revision', 'control_id']),
  'browser.session_close': schema({ browser_session_id: identifier }, ['browser_session_id'])
});

const descriptions = Object.freeze({
  'browser.session_start': 'Open a public HTTPS page in a new visible temporary browser session.',
  'browser.inspect_links': 'Inspect bounded visible links from the current browser page.',
  'browser.inspect_page': 'Inspect bounded visible page text and safe interactive controls.',
  'browser.follow_link': 'Follow one previously inspected public HTTPS link after confirmation.',
  'browser.fill_field': 'Enter bounded non-sensitive text into one previously inspected visible field after confirmation.',
  'browser.activate_control': 'Activate one previously inspected safe visible browser control after confirmation.',
  'browser.session_close': 'Close an owned temporary browser session.'
});
const definitions = Object.freeze({
  'browser.session_start': { name: 'browser.session_start', version: '0.1.0', description: descriptions['browser.session_start'], risk_tier: 'T1', side_effect: 'browser_navigation', network: true, data_egress: 'external_destination', requires_confirmation: true, timeout_ms: REQUEST_TIMEOUT_MS, output_limit: 8192, parameters: browserSchemas['browser.session_start'], input_schema: browserSchemas['browser.session_start'] },
  'browser.inspect_links': { name: 'browser.inspect_links', version: '0.1.0', description: descriptions['browser.inspect_links'], risk_tier: 'T1', side_effect: 'browser_read', network: true, data_egress: 'none', requires_confirmation: false, timeout_ms: REQUEST_TIMEOUT_MS, output_limit: 65536, parameters: browserSchemas['browser.inspect_links'], input_schema: browserSchemas['browser.inspect_links'] },
  'browser.inspect_page': { name: 'browser.inspect_page', version: '0.1.0', description: descriptions['browser.inspect_page'], risk_tier: 'T1', side_effect: 'browser_read', network: true, data_egress: 'none', requires_confirmation: false, timeout_ms: REQUEST_TIMEOUT_MS, output_limit: 65536, parameters: browserSchemas['browser.inspect_page'], input_schema: browserSchemas['browser.inspect_page'] },
  'browser.follow_link': { name: 'browser.follow_link', version: '0.1.0', description: descriptions['browser.follow_link'], risk_tier: 'T2', side_effect: 'browser_navigation', network: true, data_egress: 'external_destination', requires_confirmation: true, timeout_ms: REQUEST_TIMEOUT_MS, output_limit: 8192, parameters: browserSchemas['browser.follow_link'], input_schema: browserSchemas['browser.follow_link'] },
  'browser.fill_field': { name: 'browser.fill_field', version: '0.1.0', description: descriptions['browser.fill_field'], risk_tier: 'T3', side_effect: 'browser_input', network: true, data_egress: 'external_destination', requires_confirmation: true, timeout_ms: REQUEST_TIMEOUT_MS, output_limit: 8192, parameters: browserSchemas['browser.fill_field'], input_schema: browserSchemas['browser.fill_field'] },
  'browser.activate_control': { name: 'browser.activate_control', version: '0.1.0', description: descriptions['browser.activate_control'], risk_tier: 'T3', side_effect: 'browser_activation', network: true, data_egress: 'external_destination', requires_confirmation: true, timeout_ms: REQUEST_TIMEOUT_MS, output_limit: 8192, parameters: browserSchemas['browser.activate_control'], input_schema: browserSchemas['browser.activate_control'] },
  'browser.session_close': { name: 'browser.session_close', version: '0.1.0', description: descriptions['browser.session_close'], risk_tier: 'T0', side_effect: 'browser_close', network: false, data_egress: 'none', requires_confirmation: false, timeout_ms: 5000, output_limit: 4096, parameters: browserSchemas['browser.session_close'], input_schema: browserSchemas['browser.session_close'] }
});

function validate(name, input) {
  const args = exactObject(input, Object.keys(browserSchemas[name] ?? {}).length ? Object.keys(browserSchemas[name].properties) : [], browserSchemas[name]?.required ?? []);
  if (name === 'browser.session_start') boundedString(args.url, 'url', { min: 1, max: MAX_URL });
  else { boundedString(args.browser_session_id, 'browser_session_id', { min: 1, max: 128, identifier: true }); if (name === 'browser.inspect_links' && own(args, 'limit')) boundedInteger(args.limit, 'limit', 1, MAX_LINKS); if (name === 'browser.inspect_page') { if (own(args, 'max_text')) boundedInteger(args.max_text, 'max_text', 1, MAX_PAGE_TEXT); if (own(args, 'max_controls')) boundedInteger(args.max_controls, 'max_controls', 1, MAX_CONTROLS); } if (name === 'browser.follow_link' || name === 'browser.fill_field' || name === 'browser.activate_control') { boundedString(args.page_revision, 'page_revision', { min: 1, max: 128, identifier: true }); boundedString(args.control_id ?? args.link_id, name === 'browser.follow_link' ? 'link_id' : 'control_id', { min: 1, max: 128, identifier: true }); } if (name === 'browser.fill_field') boundedString(args.value, 'value', { min: 0, max: MAX_FIELD_VALUE }); }
  return structuredClone(args);
}

function ipv4Private(value) {
  const octets = value.split('.').map(Number); if (octets.length !== 4 || octets.some(part => !Number.isInteger(part) || part < 0 || part > 255)) return true;
  const [a, b, c] = octets; return a === 0 || a === 10 || a === 127 || a === 169 && b === 254 || a === 172 && b >= 16 && b <= 31 || a === 192 && (b === 0 || b === 168) || a === 198 && (b === 18 || b === 19 || b === 51) || a === 203 && b === 0 && c === 113 || a >= 224 || a === 100 && b >= 64 && b <= 127;
}

function ipv6Private(value) {
  const normalized = value.toLowerCase().replace(/^\[|\]$/g, ''); if (!normalized || normalized === '::' || normalized === '::1') return true;
  if (normalized.startsWith('::ffff:')) return ipv4Private(normalized.slice(7));
  const groups = normalized.split('::'); if (groups.length > 2) return true; const left = groups[0] ? groups[0].split(':') : []; const right = groups[1] ? groups[1].split(':') : []; if ([...left, ...right].some(group => !/^[0-9a-f]{1,4}$/u.test(group))) return true; const count = left.length + right.length; if ((groups.length === 1 && count !== 8) || (groups.length === 2 && count >= 8)) return true;
  const first = Number.parseInt(left[0] ?? right[0] ?? '0', 16); const second = Number.parseInt(left[1] ?? right[1] ?? '0', 16); return (first & 0xfe00) === 0xfc00 || (first & 0xffc0) === 0xfe80 || (first & 0xffc0) === 0xfec0 || (first & 0xff00) === 0xff00 || first === 0x2001 && second === 0xdb8;
}

function hostIsPrivate(host) { const value = host.replace(/^\[|\]$/g, '').toLowerCase(); const kind = isIP(value); return kind === 4 ? ipv4Private(value) : kind === 6 ? ipv6Private(value) : value === 'localhost' || value.endsWith('.localhost') || value.endsWith('.local') || value.endsWith('.internal') || value.endsWith('.lan') || value.endsWith('.home.arpa'); }

function checkUrlShape(raw) {
  if (typeof raw !== 'string' || Buffer.byteLength(raw, 'utf8') > MAX_URL) throw new ProviderToolError('provider_destination_rejected', 'URL exceeds bound');
  let url; try { url = new URL(raw); } catch { throw new ProviderToolError('provider_destination_rejected', 'URL is invalid'); }
  if (url.protocol !== 'https:' || url.username || url.password || url.hostname === '') throw new ProviderToolError('provider_destination_rejected', 'only public HTTPS URLs are accepted');
  if (url.port && url.port !== '443') throw new ProviderToolError('provider_destination_rejected', 'only HTTPS port 443 is accepted');
  return url;
}

async function publicAddress(host, resolve) {
  const value = host.replace(/^\[|\]$/g, ''); if (hostIsPrivate(value)) throw new ProviderToolError('provider_destination_rejected', 'private destination');
  if (isIP(value)) return value;
  let addresses; try { addresses = await resolve(value); } catch { throw new ProviderToolError('provider_destination_rejected', 'destination DNS unavailable'); }
  if (!Array.isArray(addresses) || addresses.length < 1 || addresses.length > 16) throw new ProviderToolError('provider_destination_rejected', 'destination DNS response invalid');
  const values = addresses.map(entry => typeof entry === 'string' ? entry : entry?.address); for (const address of values) if (typeof address !== 'string' || isIP(address) === 0 || hostIsPrivate(address)) throw new ProviderToolError('provider_destination_rejected', 'destination resolves to a private or non-literal address'); return values[0];
}
async function publicUrl(raw, resolve) {
  const url = checkUrlShape(raw); await publicAddress(url.hostname, resolve); return url;
}

function boundedText(value, max) { return typeof value === 'string' ? value.slice(0, max) : ''; }
function unsafeControl(control) { const text = `${control?.label ?? ''} ${control?.type ?? ''} ${control?.href ?? ''} ${control?.form_action ?? ''}`.toLowerCase(); return /password|file|hidden|delete|remove|purchase|buy|checkout|pay|payment|credit|card|cvv|bank|transfer|login|log in|sign in|account|security|download|upload|credential|token/u.test(text); }
function actionField(control) { return control?.kind === 'field' && ['input', 'textarea'].includes(control.tag) && ['text', 'search', 'email', 'tel', 'url'].includes(control.type || 'text') && !control.disabled && !control.readonly && !unsafeControl(control); }
function controlDigest(control) { return digest({ kind: control.kind, tag: control.tag, type: control.type, label: control.label, form_action: control.form_action, href: control.href, index: control.index }); }
async function waitChildClosed(child) { if (!child || !Number.isInteger(child.pid) || child.exitCode !== null && child.exitCode !== undefined || child.signalCode) return; await withTimeout(() => new Promise(resolve => { const done = () => { child.off?.('close', done); child.off?.('exit', done); resolve(); }; child.once?.('close', done); child.once?.('exit', done); }), undefined, CLEANUP_TIMEOUT_MS).catch(() => {}); }
async function killChild(child, killProcess, platform = process.platform) { if (!child) return; try { if (killProcess) await withTimeout(() => killProcess(child), undefined, CLEANUP_TIMEOUT_MS); else if (platform === 'win32' && Number.isInteger(child.pid)) await withTimeout(() => new Promise(resolve => { const killer = spawn('taskkill.exe', ['/PID', String(child.pid), '/T', '/F'], { shell: false, windowsHide: true, stdio: 'ignore' }); killer.once('close', resolve); killer.once('error', resolve); }), undefined, CLEANUP_TIMEOUT_MS); else if (Number.isInteger(child.pid) && platform !== 'win32') { try { process.kill(-child.pid, 'SIGTERM'); } catch { child.kill?.('SIGTERM'); } await waitChildClosed(child); try { process.kill(-child.pid, 'SIGKILL'); } catch { /* group may already be gone */ } } else child.kill?.('SIGTERM'); } catch { /* cleanup is best effort */ } await waitChildClosed(child); }
function ownTempDir(directory) { return typeof directory === 'string' && basename(directory).startsWith('lae-browser-') && dirname(directory) === tmpdir(); }
function withTimeout(task, signal, timeoutMs) { return new Promise((resolve, reject) => { let settled = false; let timer; const finish = (fn, value) => { if (settled) return; settled = true; if (timer) clearTimeout(timer); signal?.removeEventListener('abort', abort); fn(value); }; const abort = () => finish(reject, new ProviderToolError('provider_cancelled')); signal?.addEventListener('abort', abort, { once: true }); if (signal?.aborted) return abort(); timer = setTimeout(() => finish(reject, new ProviderToolError('provider_timeout')), timeoutMs); Promise.resolve().then(task).then(value => finish(resolve, value), error => finish(reject, error)); }); }
function waitForChildOrTask(child, task, signal, timeoutMs) { return new Promise((resolve, reject) => { let settled = false; const controller = new AbortController(); const finish = (fn, value) => { if (settled) return; settled = true; clearTimeout(timer); signal?.removeEventListener('abort', abort); child.off?.('error', onError); child.off?.('exit', onExit); controller.abort(); fn(value); }; const abort = () => finish(reject, new ProviderToolError('provider_cancelled')); const onError = error => finish(reject, new ProviderToolError('provider_failed', error?.message ?? 'browser process failed')); const onExit = (code, childSignal) => finish(reject, new ProviderToolError('provider_failed', `browser exited during startup (${code ?? childSignal ?? 'unknown'})`)); const timer = setTimeout(() => finish(reject, new ProviderToolError('provider_timeout')), timeoutMs); child.once('error', onError); child.once('exit', onExit); signal?.addEventListener('abort', abort, { once: true }); if (signal?.aborted) return abort(); Promise.resolve().then(() => task(controller.signal)).then(value => finish(resolve, value), error => finish(reject, error)); }); }
async function readBoundedResponse(response, maxBytes) { const declared = Number(response.headers?.get?.('content-length') ?? 0); if (declared > maxBytes) throw new ProviderToolError('provider_response_too_large'); const reader = response.body?.getReader?.(); if (!reader) throw new ProviderToolError('provider_invalid_response'); const chunks = []; let total = 0; try { while (true) { const part = await reader.read(); if (part.done) break; const chunk = part.value instanceof Uint8Array ? part.value : new Uint8Array(part.value); total += chunk.byteLength; if (total > maxBytes) { await reader.cancel().catch(() => {}); throw new ProviderToolError('provider_response_too_large'); } chunks.push(chunk); } } finally { reader.releaseLock?.(); } const output = new Uint8Array(total); let offset = 0; for (const chunk of chunks) { output.set(chunk, offset); offset += chunk.byteLength; } return new TextDecoder('utf-8', { fatal: true }).decode(output); }

export class CdpClient {
  constructor({ port, resolve, fetchImpl = globalThis.fetch, WebSocketImpl = globalThis.WebSocket } = {}) { this.port = port; this.resolve = resolve; this.fetchImpl = fetchImpl; this.WebSocketImpl = WebSocketImpl; this.socket = null; this.nextId = 1; this.pending = new Map(); this.events = []; this.eventWaiters = []; }
  async connect(signal) {
    if (typeof this.fetchImpl !== 'function' || typeof this.WebSocketImpl !== 'function') throw new ProviderToolError('provider_unconfigured', 'CDP requires built-in fetch and WebSocket');
    const response = await this.fetchImpl(`http://127.0.0.1:${this.port}/json/list`, { signal, redirect: 'error' }); if (!response.ok) throw new ProviderToolError('provider_unconfigured', 'CDP endpoint unavailable'); const raw = await readBoundedResponse(response, 65536); let targets; try { targets = JSON.parse(raw); } catch { throw new ProviderToolError('provider_invalid_response'); } const target = Array.isArray(targets) ? targets.slice(0, 16).find(item => item?.type === 'page' && typeof item.webSocketDebuggerUrl === 'string') : null; if (!target) throw new ProviderToolError('provider_unconfigured', 'CDP page target unavailable');
    const endpoint = new URL(target.webSocketDebuggerUrl); if (endpoint.protocol !== 'ws:' || endpoint.hostname !== '127.0.0.1' || endpoint.port !== String(this.port)) throw new ProviderToolError('provider_unconfigured', 'CDP target is not loopback bound');
    await new Promise((resolve, reject) => { const socket = new this.WebSocketImpl(endpoint.href); this.socket = socket; try { socket.binaryType = 'arraybuffer'; } catch { /* fake sockets may not expose binaryType */ } const fail = error => reject(error instanceof Error ? error : new Error('CDP connection failed')); socket.addEventListener('open', resolve, { once: true }); socket.addEventListener('error', fail, { once: true }); socket.addEventListener('close', () => { for (const item of this.pending.values()) item.reject(new ProviderToolError('provider_cancelled')); this.pending.clear(); }); socket.addEventListener('message', event => { try { const data = event?.data; if (typeof data === 'string') this.onMessage(data); else if (data instanceof ArrayBuffer || ArrayBuffer.isView(data)) this.onMessage(new TextDecoder('utf-8', { fatal: true }).decode(data)); else this.close(); } catch { this.close(); } }); });
    await this.send('Page.enable', {}); await this.send('Network.enable', {}); await this.send('Fetch.enable', { patterns: [{ urlPattern: '*', requestStage: 'Request' }] });
  }
  onMessage(raw) { if (typeof raw !== 'string' || Buffer.byteLength(raw, 'utf8') > 262144) { this.close(); return; } let message; try { message = JSON.parse(raw); } catch { return; } if (message.id && this.pending.has(message.id)) { const item = this.pending.get(message.id); this.pending.delete(message.id); if (message.error) item.reject(new ProviderToolError('provider_failed', message.error.message ?? 'CDP command failed')); else item.resolve(message.result ?? {}); return; } if (message.method) { const index = this.eventWaiters.findIndex(item => item.method === message.method); if (index >= 0) this.eventWaiters.splice(index, 1)[0].resolve(message); else { if (this.events.length >= 128) this.events.shift(); this.events.push(message); } if (message.method === 'Fetch.requestPaused') this.guardRequest(message.params).catch(() => {}); } }
  async guardRequest(params) { const id = params?.requestId; const raw = params?.request?.url; if (typeof id !== 'string') return; try { await withTimeout(() => publicUrl(raw, this.resolve), undefined, 5000); await this.send('Fetch.continueRequest', { requestId: id }); } catch { await this.send('Fetch.failRequest', { requestId: id, errorReason: 'BlockedByClient' }).catch(() => {}); } }
  send(method, params) { if (!this.socket) return Promise.reject(new ProviderToolError('provider_unconfigured')); if (this.pending.size >= 64) return Promise.reject(new ProviderToolError('provider_response_too_large')); const id = this.nextId++; return new Promise((resolve, reject) => { this.pending.set(id, { resolve, reject }); try { this.socket.send(JSON.stringify({ id, method, params })); } catch (error) { this.pending.delete(id); reject(error); } }); }
  async waitLoad(signal) { const index = this.events.findIndex(event => event.method === 'Page.loadEventFired'); if (index >= 0) { this.events.splice(index, 1); return; } await withTimeout(() => new Promise((resolve, reject) => { if (!this.socket) return reject(new ProviderToolError('provider_cancelled')); this.eventWaiters.push({ method: 'Page.loadEventFired', resolve, reject }); }), signal, REQUEST_TIMEOUT_MS); }
  async navigate(url, signal) { checkAborted(signal); await this.send('Page.navigate', { url: url.href }); await this.waitLoad(signal); checkAborted(signal); }
  async inspect(signal) { checkAborted(signal); const output = await this.send('Runtime.evaluate', { expression: PAGE_SCRIPT, returnByValue: true, awaitPromise: false }); const value = output?.result?.value; if (!value || typeof value !== 'object') throw new ProviderToolError('provider_invalid_response'); return value; }
  async inspectPage(signal) { return this.inspect(signal); }
  async fillControl(index, value, signal, expected = {}) { checkAborted(signal); if (!Number.isInteger(index) || index < 0 || index >= MAX_CONTROLS) throw new ProviderToolError('browser_control_changed'); const shape = JSON.stringify({ tag: expected.tag, type: expected.type, label: expected.label, form_action: expected.form_action, href: expected.href }); const expression = `(() => { const visible = a => { const s = getComputedStyle(a); const r = a.getBoundingClientRect(); return s.display !== 'none' && s.visibility !== 'hidden' && r.width > 0 && r.height > 0; }; const all = Array.from(document.querySelectorAll('input,textarea,select,button,[role=button]')).filter(visible); const a = all[${index}]; const expected = ${shape}; const actual = a && { tag: a.tagName.toLowerCase(), type: (a.type || '').toLowerCase(), label: (a.getAttribute('aria-label') || a.innerText || a.textContent || '').replace(/\\s+/g, ' ').trim().slice(0, ${MAX_LABEL}), form_action: a.form?.action ? a.form.action.slice(0, ${MAX_URL}) : '', href: a.href ? a.href.slice(0, ${MAX_URL}) : '' }; if (!a || JSON.stringify(actual) !== JSON.stringify(expected) || !['input','textarea','select'].includes(actual.tag) || a.disabled || a.readOnly || ['password','file','hidden'].includes(actual.type)) return false; a.focus(); a.value = ${JSON.stringify(value)}; a.dispatchEvent(new Event('input', { bubbles: true })); a.dispatchEvent(new Event('change', { bubbles: true })); return true; })()`; const output = await this.send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: false }); if (output?.result?.value !== true) throw new ProviderToolError('browser_control_changed'); }
  async activateControl(index, signal, expected = {}) { checkAborted(signal); if (!Number.isInteger(index) || index < 0 || index >= MAX_CONTROLS) throw new ProviderToolError('browser_control_changed'); const shape = JSON.stringify({ tag: expected.tag, type: expected.type, label: expected.label, form_action: expected.form_action, href: expected.href }); const expression = `(() => { const visible = a => { const s = getComputedStyle(a); const r = a.getBoundingClientRect(); return s.display !== 'none' && s.visibility !== 'hidden' && r.width > 0 && r.height > 0; }; const all = Array.from(document.querySelectorAll('input,textarea,select,button,[role=button]')).filter(visible); const a = all[${index}]; const expected = ${shape}; const actual = a && { tag: a.tagName.toLowerCase(), type: (a.type || '').toLowerCase(), label: (a.getAttribute('aria-label') || a.innerText || a.textContent || '').replace(/\\s+/g, ' ').trim().slice(0, ${MAX_LABEL}), form_action: a.form?.action ? a.form.action.slice(0, ${MAX_URL}) : '', href: a.href ? a.href.slice(0, ${MAX_URL}) : '' }; if (!a || JSON.stringify(actual) !== JSON.stringify(expected) || actual.tag !== 'button' || actual.type !== 'button' || actual.form_action || actual.href || a.disabled) return false; a.click(); return true; })()`; const output = await this.send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: false }); if (output?.result?.value !== true) throw new ProviderToolError('browser_control_changed'); }
  close() { const failure = new ProviderToolError('provider_cancelled'); for (const item of this.pending.values()) item.reject(failure); this.pending.clear(); for (const waiter of this.eventWaiters) waiter.reject(failure); this.eventWaiters = []; this.events = []; try { this.socket?.close(); } catch { /* cleanup */ } this.socket = null; }
}

async function waitDevtoolsPort(directory, signal, timeoutMs) { const deadline = Date.now() + timeoutMs; while (Date.now() < deadline) { checkAborted(signal); let handle; try { handle = await open(join(directory, 'DevToolsActivePort'), 'r'); const buffer = Buffer.alloc(1024); const { bytesRead } = await handle.read(buffer, 0, buffer.length, 0); const lines = buffer.subarray(0, bytesRead).toString('utf8').split(/\r?\n/u); const port = Number(lines[0]); if (Number.isInteger(port) && port > 0 && port < 65536) return { port }; } catch { /* browser has not published its endpoint yet */ } finally { await handle?.close().catch(() => {}); } await new Promise(resolve => setTimeout(resolve, 25)); } throw new ProviderToolError('provider_timeout', 'browser CDP endpoint did not start'); }

async function createValidatingProxy(resolve) { const sockets = new Set(); const server = createServer(socket => { if (sockets.size >= 32) return socket.end('HTTP/1.1 429 Too Many Requests\r\n\r\n'); sockets.add(socket); socket.once('close', () => sockets.delete(socket)); socket.setTimeout(5000, () => socket.destroy()); let data = ''; const onData = chunk => { data += chunk.toString('latin1'); if (Buffer.byteLength(data, 'latin1') > 8192) return socket.destroy(); const end = data.indexOf('\r\n\r\n'); if (end < 0) return; socket.off('data', onData); const line = data.slice(0, data.indexOf('\r\n')); const match = line.match(/^CONNECT\s+([^\s:]+|\[[^\]]+\]):(\d{1,5})\s+HTTP\/1\.1$/u); if (!match || match[2] !== '443') return socket.end('HTTP/1.1 403 Forbidden\r\n\r\n'); const host = match[1].replace(/^\[|\]$/g, ''); withTimeout(() => publicAddress(host, resolve), undefined, 5000).then(address => { const upstream = createConnection({ host: address, port: 443 }); sockets.add(upstream); upstream.once('close', () => sockets.delete(upstream)); upstream.setTimeout(5000, () => upstream.destroy()); upstream.once('connect', () => { socket.write('HTTP/1.1 200 Connection Established\r\n\r\n'); socket.pipe(upstream); upstream.pipe(socket); }); upstream.once('error', () => socket.destroy()); }).catch(() => socket.end('HTTP/1.1 403 Forbidden\r\n\r\n')); }; socket.on('data', onData); }); await new Promise((resolveListen, reject) => { server.once('error', reject); server.listen(0, '127.0.0.1', resolveListen); }); return { port: server.address().port, close: () => new Promise(resolveClose => { for (const socket of sockets) socket.destroy(); server.close(() => resolveClose()); }) }; }

function normalizeActionOrigins(origins) {
  if (!Array.isArray(origins) || origins.length > 16 || origins.length === 0) throw new TypeError('safe browser actions require configured origins');
  const values = origins.map(value => {
    if (typeof value !== 'string' || Buffer.byteLength(value, 'utf8') > 512) throw new TypeError('invalid browser action origin');
    let url; try { url = new URL(value); } catch { throw new TypeError('invalid browser action origin'); }
    if (url.protocol !== 'https:' || url.username || url.password || url.pathname !== '/' || url.search || url.hash || url.port && url.port !== '443' || hostIsPrivate(url.hostname)) throw new TypeError('invalid browser action origin');
    return url.origin;
  });
  return new Set(values);
}

export class BrowserActionProvider {
  constructor({ enabled = false, executable, allowlist = [], spawn: spawnImpl = spawn, killProcess, mkdtempImpl = mkdtemp, rmImpl = rm, proxyFactory = createValidatingProxy, waitDevtoolsPortImpl = waitDevtoolsPort, resolve = async host => (await dns.lookup(host, { all: true, verbatim: true })).map(item => item.address), cdpFactory, fetchImpl, WebSocketImpl, requestTimeoutMs = REQUEST_TIMEOUT_MS, platform = process.platform, experimentalMutations = false, safeActions = false, actionOrigins = [], testOnly = false } = {}) {
    if (executable !== undefined && !absoluteLocalPath(executable) || !Array.isArray(allowlist) || allowlist.length > 16 || allowlist.some(item => !absoluteLocalPath(item))) throw new TypeError('invalid browser executable/allowlist');
    if (!Number.isInteger(requestTimeoutMs) || requestTimeoutMs < 100 || requestTimeoutMs > 120000) throw new TypeError('invalid browser timeout');
    if (experimentalMutations === true && testOnly !== true) throw new TypeError('browser mutations require test-only gate');
    if (safeActions === true && experimentalMutations === true || safeActions === true && testOnly === true) throw new TypeError('safe browser actions cannot share test-only gates');
    this.enabled = enabled === true; Object.defineProperty(this, 'testOnly', { enumerable: false, value: testOnly === true }); this.experimentalMutations = experimentalMutations === true; this.safeActions = safeActions === true; this.actionOrigins = this.safeActions ? normalizeActionOrigins(actionOrigins) : new Set(); this.executable = executable; this.allowlist = new Set(allowlist); this.spawn = spawnImpl; this.killProcess = killProcess; this.mkdtemp = mkdtempImpl; this.rm = rmImpl; this.proxyFactory = proxyFactory; this.waitDevtoolsPort = waitDevtoolsPortImpl; this.resolve = resolve; this.cdpFactory = cdpFactory; this.fetchImpl = fetchImpl; this.WebSocketImpl = WebSocketImpl; this.requestTimeoutMs = requestTimeoutMs; this.platform = platform; this.sessions = new Map(); this.proposals = new Map();
  }
  state() { if (!this.enabled) return 'disabled'; if (typeof this.executable !== 'string' || !this.executable || !this.allowlist.has(this.executable)) return 'unconfigured'; return 'unverified'; }
  async destination(raw, signal) { return withTimeout(() => publicUrl(raw, this.resolve), signal, this.requestTimeoutMs); }
  async actionDestination(raw, session, signal) { const destination = await this.destination(raw, signal); const currentUrl = session?.url ?? session?.href; if (this.safeActions && (!currentUrl || !this.actionOrigins.has(new URL(currentUrl).origin) || !this.actionOrigins.has(destination.origin))) throw new ProviderToolError('provider_destination_rejected', 'browser action origin is not configured'); return destination; }
  remember(call, args, binding = {}) { if (this.proposals.size >= 128 && !this.proposals.has(call.id)) this.proposals.delete(this.proposals.keys().next().value); this.proposals.set(call.id, { name: call.name, digest: digest(args), binding }); }
  consumeProposal(call, args, binding = {}) { const saved = this.proposals.get(call.id); if (!saved || saved.name !== call.name || saved.digest !== digest(args) || digest(saved.binding) !== digest(binding)) throw new ProviderToolError('provider_permission_insufficient', 'browser action requires a matching preview'); this.proposals.delete(call.id); }
  async preview(call) { const args = validate(call.name, call.arguments); const mutating = call.name === 'browser.fill_field' || call.name === 'browser.activate_control'; if (mutating && !this.experimentalMutations && !this.safeActions) throw new ProviderToolError('provider_unconfigured', 'browser mutations are disabled by default'); if (mutating) { const session = this.sessions.get(args.browser_session_id); if (!session || session.closed || session.revision !== args.page_revision) throw new ProviderToolError('browser_session_stale'); const control = session.controls?.get(args.control_id); if (!control || unsafeControl(control) || this.safeActions && call.name === 'browser.fill_field' && !actionField(control) || this.safeActions && call.name === 'browser.activate_control' && (control.kind !== 'control' || control.tag !== 'button' || control.type !== 'button' || control.form_action || control.href || control.disabled)) throw new ProviderToolError('browser_control_changed'); const destination = await this.actionDestination(control.form_action || control.href || session.url, session, call.signal); this.remember(call, args, { session_id: session.id, page_revision: session.revision, control_digest: control.digest, origin: new URL(session.url).origin, destination: destination.href }); const preview = { provider: 'browser_actions', action: call.name, browser_session_id: session.id, page_revision: session.revision, control_id: control.id, control_label: control.label, destination: destination.href, data_egress: 'external_destination' }; if (call.name === 'browser.fill_field') { preview.value_preview = boundedText(args.value, 256); preview.value_truncated = args.value.length > 256; } return preview; } const args0 = validate(call.name, call.arguments); if (call.name === 'browser.session_start') { const url = await this.destination(args0.url, call.signal); if (this.safeActions && !this.actionOrigins.has(url.origin)) throw new ProviderToolError('provider_destination_rejected', 'browser action origin is not configured'); this.remember(call, args0); return { provider: 'browser_actions', action: 'session_start', destination: url.href, data_egress: 'external_destination' }; } if (call.name === 'browser.follow_link') { const session = this.sessions.get(args0.browser_session_id); if (!session || session.closed || session.revision !== args0.page_revision) throw new ProviderToolError('browser_session_stale'); const link = session.links.get(args0.link_id); if (!link) throw new ProviderToolError('browser_link_changed'); await this.destination(link.url, call.signal); this.remember(call, args0); return { provider: 'browser_actions', action: 'follow_link', browser_session_id: session.id, page_revision: session.revision, link_id: link.id, destination: link.url, data_egress: 'external_destination' }; } return { provider: 'browser_actions', action: call.name, browser_session_id: args0.browser_session_id }; }
  async authorize(call) { validate(call.name, call.arguments); return { kind: 'policy' }; }
  async execute(call) { try { const args = validate(call.name, call.arguments); return await this._execute(call, args); } catch (error) { if (error?.code === 'invalid_tool_arguments') throw error; return failureResult(call, error); } }
  async _execute(call, args) {
    checkAborted(call.signal); if ((call.name === 'browser.fill_field' || call.name === 'browser.activate_control') && !this.experimentalMutations && !this.safeActions) return failureResult(call, new ProviderToolError('provider_unconfigured')); if (this.state() === 'disabled') return failureResult(call, new ProviderToolError('provider_disabled')); if (this.state() === 'unconfigured') return failureResult(call, new ProviderToolError('provider_unconfigured'));
    if (call.name === 'browser.session_close') return this.closeSession(call, args);
    if (call.name === 'browser.inspect_links') return this.inspectLinks(call, args);
    if (call.name === 'browser.inspect_page') return this.inspectPage(call, args);
    if (call.name === 'browser.session_start') { if (call.authorization?.kind !== 'user_confirmation') return failureResult(call, new ProviderToolError('provider_permission_insufficient')); this.consumeProposal(call, args); return this.startSession(call, args); }
    if (call.name === 'browser.follow_link') { if (call.authorization?.kind !== 'user_confirmation') return failureResult(call, new ProviderToolError('provider_permission_insufficient')); this.consumeProposal(call, args); return this.followLink(call, args); }
    if (call.name === 'browser.fill_field' || call.name === 'browser.activate_control') { if (call.authorization?.kind !== 'user_confirmation') return failureResult(call, new ProviderToolError('provider_permission_insufficient')); const session = this.sessions.get(args.browser_session_id); const control = session?.controls?.get(args.control_id); const destination = control && await this.actionDestination(control.form_action || control.href || session.url, session, call.signal); this.consumeProposal(call, args, { session_id: session?.id, page_revision: session?.revision, control_digest: control?.digest, origin: session ? new URL(session.url).origin : null, destination: destination?.href }); return call.name === 'browser.fill_field' ? this.fillField(call, args) : this.activateControl(call, args); }
    throw new ProviderToolError('invalid_tool_arguments');
  }
  async startSession(call, args) {
    const url = await this.destination(args.url, call.signal); if (this.safeActions && !this.actionOrigins.has(url.origin)) throw new ProviderToolError('provider_destination_rejected', 'browser action origin is not configured'); const directory = await this.mkdtemp(join(tmpdir(), 'lae-browser-')); if (!ownTempDir(directory)) throw new ProviderToolError('provider_failed', 'temporary profile path is not owned');
    let child; let cdp; let proxy; try {
      const proxyResolve = this.safeActions ? async host => { const value = host.replace(/^\[|\]$/g, '').toLowerCase(); if (![...this.actionOrigins].some(origin => new URL(origin).hostname === value)) throw new ProviderToolError('provider_destination_rejected', 'browser action egress origin is not configured'); return this.resolve(host); } : this.resolve; proxy = await withTimeout(() => this.proxyFactory(proxyResolve), call.signal, this.requestTimeoutMs); if (!proxy || !Number.isInteger(proxy.port) || proxy.port < 1 || proxy.port > 65535) throw new ProviderToolError('provider_failed', 'browser proxy did not start'); const argv = [`--user-data-dir=${directory}`, '--no-first-run', '--no-default-browser-check', '--disable-extensions', '--disable-sync', '--disable-background-networking', '--proxy-bypass-list=<-loopback>', `--proxy-server=http://127.0.0.1:${proxy.port}`, '--remote-debugging-address=127.0.0.1', '--remote-debugging-port=0']; child = this.spawn(this.executable, argv, { shell: false, windowsHide: true, detached: this.platform !== 'win32', stdio: 'ignore' }); if (!child || typeof child.once !== 'function') throw new ProviderToolError('provider_failed', 'browser process did not start'); const devtools = await waitForChildOrTask(child, startupSignal => this.waitDevtoolsPort(directory, startupSignal, this.requestTimeoutMs), call.signal, this.requestTimeoutMs); cdp = this.cdpFactory ? await this.cdpFactory({ port: devtools.port, resolve: this.resolve, fetchImpl: this.fetchImpl, WebSocketImpl: this.WebSocketImpl, signal: call.signal }) : new CdpClient({ port: devtools.port, resolve: this.resolve, fetchImpl: this.fetchImpl, WebSocketImpl: this.WebSocketImpl }); await withTimeout(() => cdp.connect(call.signal), call.signal, this.requestTimeoutMs); await withTimeout(() => cdp.navigate(url, call.signal), call.signal, this.requestTimeoutMs); const page = await withTimeout(() => cdp.inspect(call.signal), call.signal, this.requestTimeoutMs); const finalUrl = await this.actionDestination(page.url, { url: url.href }, call.signal); const session = await this.recordSession({ directory, child, cdp, proxy, url: finalUrl, page }); return result(call, 'ok', { provider: 'browser_actions', state: 'ready', browser_session_id: session.id, url: session.url, title: session.title, page_revision: session.revision });
    } catch (error) { try { await cdp?.close?.(); } catch { /* continue cleanup */ } try { await killChild(child, this.killProcess, this.platform); } catch { /* continue cleanup */ } try { await withTimeout(() => proxy?.close?.(), undefined, CLEANUP_TIMEOUT_MS); } catch { /* continue cleanup */ } await this.removeDirectory(directory); throw error; }
  }
  async recordSession({ directory, child, cdp, proxy, url, page }) { const id = `browser_${randomUUID().replaceAll('-', '')}`; const session = { id, directory, child, cdp, proxy, url: url.href, title: boundedText(page.title, MAX_PAGE_TITLE), text: '', revision: '', links: new Map(), controls: new Map(), linkTruncated: false, controlTruncated: false, closed: false, cleanupPromise: null }; this.updatePage(session, page); if (this.sessions.size >= MAX_SESSIONS) { const oldest = this.sessions.keys().next().value; await this.closeStored(this.sessions.get(oldest)); this.sessions.delete(oldest); } this.sessions.set(id, session); child.once('exit', () => { session.closed = true; void this.cleanupStored(session).catch(() => {}); }); return session; }
  updatePage(session, page) { const current = checkUrlShape(page.url); session.url = current.href; session.title = boundedText(page.title, MAX_PAGE_TITLE); session.text = boundedText(page.text, MAX_PAGE_TEXT); const source = Array.isArray(page.links) ? page.links : []; const links = source.slice(0, MAX_LINK_SCAN); const canonical = []; let index = 0; for (; index < links.length && canonical.length < MAX_LINKS; index++) { const candidate = links[index]; if (!candidate || typeof candidate !== 'object' || typeof candidate.href !== 'string') continue; let target; try { target = checkUrlShape(candidate.href); } catch { continue; } canonical.push({ url: target.href, label: boundedText(candidate.label, MAX_LABEL) }); } const rawControls = Array.isArray(page.controls) ? page.controls.slice(0, MAX_LINK_SCAN) : []; const controls = []; for (const candidate of rawControls) { if (!candidate || typeof candidate !== 'object' || !['field', 'control'].includes(candidate.kind)) continue; if (typeof candidate.index !== 'number' || !Number.isInteger(candidate.index) || candidate.index < 0 || candidate.index >= MAX_LINK_SCAN) continue; controls.push({ kind: candidate.kind, index: candidate.index, tag: boundedText(candidate.tag, 32), type: boundedText(candidate.type, 32).toLowerCase(), label: boundedText(candidate.label, MAX_LABEL), value: boundedText(candidate.value, MAX_FIELD_VALUE), disabled: candidate.disabled === true, readonly: candidate.readonly === true, form_action: boundedText(candidate.form_action, MAX_URL), href: boundedText(candidate.href, MAX_URL) }); } const revision = digest({ url: session.url, title: session.title, text: session.text, links: canonical, controls: controls.map(control => ({ ...control, value: control.kind === 'field' && control.type !== 'password' ? control.value : '' })) }); session.revision = revision; session.links = new Map(canonical.map((item, itemIndex) => { const id = `link_${digest({ revision, index: itemIndex, url: item.url }).slice(0, 24)}`; return [id, { id, url: item.url, label: item.label }]; })); session.controls = new Map(controls.map((item, itemIndex) => { const id = `control_${digest({ revision, index: itemIndex, kind: item.kind, label: item.label }).slice(0, 24)}`; return [id, { ...item, id, digest: controlDigest(item) }]; })); session.linkTruncated = source.length > MAX_LINK_SCAN || index < links.length || canonical.length >= MAX_LINKS && source.length > canonical.length; session.controlTruncated = (Array.isArray(page.controls) ? page.controls.length : 0) > MAX_LINK_SCAN || controls.length >= MAX_CONTROLS; return session; }
  async inspectLinks(call, args) { const session = this.sessions.get(args.browser_session_id); if (!session || session.closed) return failureResult(call, new ProviderToolError('browser_session_stale')); const page = await withTimeout(() => session.cdp.inspect(call.signal), call.signal, this.requestTimeoutMs); const current = await this.destination(page.url, call.signal); if (current.href !== page.url) throw new ProviderToolError('browser_session_stale'); this.updatePage(session, page); const links = [...session.links.values()].slice(0, args.limit ?? MAX_LINKS); return result(call, 'ok', { provider: 'browser_actions', state: 'ready', browser_session_id: session.id, url: session.url, title: session.title, page_revision: session.revision, links, truncated: session.linkTruncated || session.links.size > links.length }); }
  async inspectPage(call, args) { const session = this.sessions.get(args.browser_session_id); if (!session || session.closed) return failureResult(call, new ProviderToolError('browser_session_stale')); const page = await withTimeout(() => (session.cdp.inspectPage ?? session.cdp.inspect).call(session.cdp, call.signal), call.signal, this.requestTimeoutMs); const current = await this.destination(page.url, call.signal); if (current.href !== page.url) throw new ProviderToolError('browser_session_stale'); this.updatePage(session, page); const controls = [...session.controls.values()].slice(0, args.max_controls ?? MAX_CONTROLS); const text = boundedText(session.text, args.max_text ?? MAX_PAGE_TEXT); return result(call, 'ok', { provider: 'browser_actions', state: 'ready', browser_session_id: session.id, url: session.url, title: session.title, page_revision: session.revision, text, controls, text_truncated: session.text.length > text.length, controls_truncated: session.controlTruncated }); }
  async refreshControlSession(call, args) { const session = this.sessions.get(args.browser_session_id); if (!session || session.closed || session.revision !== args.page_revision) throw new ProviderToolError('browser_session_stale'); const page = await withTimeout(() => (session.cdp.inspectPage ?? session.cdp.inspect).call(session.cdp, call.signal), call.signal, this.requestTimeoutMs); await this.actionDestination(page.url, session, call.signal); this.updatePage(session, page); if (session.revision !== args.page_revision) throw new ProviderToolError('browser_session_stale'); const control = session.controls.get(args.control_id); if (!control || unsafeControl(control) || this.safeActions && call.name === 'browser.fill_field' && !actionField(control) || this.safeActions && call.name === 'browser.activate_control' && (control.kind !== 'control' || control.tag !== 'button' || control.type !== 'button' || control.form_action || control.href || control.disabled)) throw new ProviderToolError('browser_control_changed'); return { session, control }; }
  async fillField(call, args) { try { const { session, control } = await this.refreshControlSession(call, args); if (control.kind !== 'field' || ['password', 'file', 'hidden'].includes(control.type) || control.disabled || control.readonly) throw new ProviderToolError('browser_control_changed'); const destination = await this.actionDestination(control.form_action || control.href || session.url, session, call.signal); await withTimeout(() => session.cdp.fillControl(control.index, args.value, call.signal, control), call.signal, this.requestTimeoutMs); const page = await withTimeout(() => (session.cdp.inspectPage ?? session.cdp.inspect).call(session.cdp, call.signal), call.signal, this.requestTimeoutMs); const finalDestination = await this.actionDestination(page.url, session, call.signal); this.updatePage(session, page); return result(call, 'ok', { provider: 'browser_actions', state: 'ready', browser_session_id: session.id, control_id: control.id, page_revision: session.revision, destination: this.safeActions ? finalDestination.href : destination.href, ...(this.safeActions ? { egress_destination: destination.href } : {}) }); } catch (error) { return failureResult(call, error); } }
  async activateControl(call, args) { try { const { session, control } = await this.refreshControlSession(call, args); if (control.kind !== 'control' || control.tag !== 'button' || control.type !== 'button' || control.form_action || control.href || control.disabled) throw new ProviderToolError('browser_control_changed'); const destination = await this.actionDestination(session.url, session, call.signal); await withTimeout(() => session.cdp.activateControl(control.index, call.signal, control), call.signal, this.requestTimeoutMs); const page = await withTimeout(() => (session.cdp.inspectPage ?? session.cdp.inspect).call(session.cdp, call.signal), call.signal, this.requestTimeoutMs); const finalDestination = await this.actionDestination(page.url, session, call.signal); this.updatePage(session, page); return result(call, 'ok', { provider: 'browser_actions', state: 'ready', browser_session_id: session.id, control_id: control.id, page_revision: session.revision, destination: finalDestination.href, egress_destination: destination.href }); } catch (error) { return failureResult(call, error); } }
  async followLink(call, args) { const session = this.sessions.get(args.browser_session_id); if (!session || session.closed) return failureResult(call, new ProviderToolError('browser_session_stale')); if (session.revision !== args.page_revision) return failureResult(call, new ProviderToolError('browser_session_stale')); const link = session.links.get(args.link_id); if (!link) return failureResult(call, new ProviderToolError('browser_link_changed')); const destination = await this.destination(link.url, call.signal); try { await withTimeout(() => session.cdp.navigate(destination, call.signal), call.signal, this.requestTimeoutMs); const page = await withTimeout(() => session.cdp.inspect(call.signal), call.signal, this.requestTimeoutMs); await this.destination(page.url, call.signal); this.updatePage(session, page); return result(call, 'ok', { provider: 'browser_actions', state: 'ready', browser_session_id: session.id, url: session.url, title: session.title, page_revision: session.revision, followed_link_id: link.id }); } catch (error) { if (error?.code === 'provider_destination_rejected') return failureResult(call, error); throw error; } }
  async closeSession(call, args) { const session = this.sessions.get(args.browser_session_id); if (!session || session.closed) return failureResult(call, new ProviderToolError('browser_session_stale')); await this.closeStored(session); this.sessions.delete(session.id); return result(call, 'ok', { provider: 'browser_actions', state: 'closed', browser_session_id: session.id, closed: true }); }
  async closeStored(session) { if (!session) return; session.closed = true; await this.cleanupStored(session); }
  async cleanupStored(session) { if (!session.cleanupPromise) session.cleanupPromise = (async () => { try { await session.cdp?.close?.(); } catch { /* continue cleanup */ } try { await killChild(session.child, this.killProcess, this.platform); } catch { /* continue cleanup */ } try { await withTimeout(() => session.proxy?.close?.(), undefined, CLEANUP_TIMEOUT_MS); } catch { /* continue cleanup */ } try { await this.removeDirectory(session.directory); } catch { /* continue cleanup */ } })(); await session.cleanupPromise; }
  async removeDirectory(directory) { if (!ownTempDir(directory)) return; try { await this.rm(directory, { recursive: true, force: true }); } catch { /* cleanup remains best effort and never broadens the target */ } }
  async shutdown() { await Promise.all([...this.sessions.values()].map(session => this.closeStored(session))); this.sessions.clear(); }
}

export function createBrowserActionTools(options = {}) { const provider = options instanceof BrowserActionProvider ? options : new BrowserActionProvider(options); return Object.fromEntries(Object.entries(definitions).filter(([name]) => (provider.experimentalMutations || provider.safeActions) || !['browser.fill_field', 'browser.activate_control'].includes(name)).map(([name, definition]) => [name, { ...definition, confirmationRequired: () => definition.requires_confirmation, authorize: call => provider.authorize({ ...call, name }), preview: call => provider.preview({ ...call, name }), execute: call => provider.execute({ ...call, name }) }])); }

export { browserSchemas, definitions as browserActionDefinitions, publicAddress, publicUrl, hostIsPrivate };
