import { mkdtemp, open, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, basename, dirname } from 'node:path';
import { randomUUID } from 'node:crypto';
import { spawn } from 'node:child_process';
import { promises as dns } from 'node:dns';
import { createConnection, createServer, isIP } from 'node:net';
import { makeToolResult } from '../agent/tool-envelope.mjs';
import { ProviderToolError, boundedInteger, boundedString, checkAborted, digest, exactObject, failureResult, own, result } from './provider-common.mjs';

const MAX_SESSIONS = 4;
const MAX_LINKS = 50;
const MAX_LINK_SCAN = 100;
const MAX_PAGE_TITLE = 512;
const MAX_LABEL = 256;
const MAX_URL = 2048;
const REQUEST_TIMEOUT_MS = 15000;
const PAGE_SCRIPT = `(() => { const visible = a => { const style = getComputedStyle(a); const rect = a.getBoundingClientRect(); return style.display !== 'none' && style.visibility !== 'hidden' && rect.width > 0 && rect.height > 0; }; const links = Array.from(document.querySelectorAll('a[href]')).slice(0, ${MAX_LINK_SCAN}).map((a, index) => ({ index, href: a.href.slice(0, ${MAX_URL}), label: (a.innerText || a.textContent || '').replace(/\\s+/g, ' ').trim().slice(0, ${MAX_LABEL}), visible: visible(a) })).filter(a => a.visible && a.href); return { url: location.href.slice(0, ${MAX_URL}), title: (document.title || '').slice(0, ${MAX_PAGE_TITLE}), links }; })()`;

const schema = (properties, required = []) => ({ type: 'object', additionalProperties: false, required, properties });
const identifier = { type: 'string', minLength: 1, maxLength: 128 };
const browserSchemas = Object.freeze({
  'browser.session_start': schema({ url: { type: 'string', minLength: 1, maxLength: MAX_URL } }, ['url']),
  'browser.inspect_links': schema({ browser_session_id: identifier, limit: { type: 'integer', minimum: 1, maximum: MAX_LINKS } }, ['browser_session_id']),
  'browser.follow_link': schema({ browser_session_id: identifier, page_revision: { type: 'string', minLength: 1, maxLength: 128 }, link_id: identifier }, ['browser_session_id', 'page_revision', 'link_id']),
  'browser.session_close': schema({ browser_session_id: identifier }, ['browser_session_id'])
});

const descriptions = Object.freeze({
  'browser.session_start': 'Open a public HTTPS page in a new visible temporary browser session.',
  'browser.inspect_links': 'Inspect bounded visible links from the current browser page.',
  'browser.follow_link': 'Follow one previously inspected public HTTPS link after confirmation.',
  'browser.session_close': 'Close an owned temporary browser session.'
});
const definitions = Object.freeze({
  'browser.session_start': { name: 'browser.session_start', version: '0.1.0', description: descriptions['browser.session_start'], risk_tier: 'T1', side_effect: 'browser_navigation', network: true, data_egress: 'external_destination', requires_confirmation: true, timeout_ms: REQUEST_TIMEOUT_MS, output_limit: 8192, parameters: browserSchemas['browser.session_start'], input_schema: browserSchemas['browser.session_start'] },
  'browser.inspect_links': { name: 'browser.inspect_links', version: '0.1.0', description: descriptions['browser.inspect_links'], risk_tier: 'T1', side_effect: 'browser_read', network: true, data_egress: 'none', requires_confirmation: false, timeout_ms: REQUEST_TIMEOUT_MS, output_limit: 65536, parameters: browserSchemas['browser.inspect_links'], input_schema: browserSchemas['browser.inspect_links'] },
  'browser.follow_link': { name: 'browser.follow_link', version: '0.1.0', description: descriptions['browser.follow_link'], risk_tier: 'T2', side_effect: 'browser_navigation', network: true, data_egress: 'external_destination', requires_confirmation: true, timeout_ms: REQUEST_TIMEOUT_MS, output_limit: 8192, parameters: browserSchemas['browser.follow_link'], input_schema: browserSchemas['browser.follow_link'] },
  'browser.session_close': { name: 'browser.session_close', version: '0.1.0', description: descriptions['browser.session_close'], risk_tier: 'T0', side_effect: 'browser_close', network: false, data_egress: 'none', requires_confirmation: false, timeout_ms: 5000, output_limit: 4096, parameters: browserSchemas['browser.session_close'], input_schema: browserSchemas['browser.session_close'] }
});

function validate(name, input) {
  const args = exactObject(input, Object.keys(browserSchemas[name] ?? {}).length ? Object.keys(browserSchemas[name].properties) : [], browserSchemas[name]?.required ?? []);
  if (name === 'browser.session_start') boundedString(args.url, 'url', { min: 1, max: MAX_URL });
  else { boundedString(args.browser_session_id, 'browser_session_id', { min: 1, max: 128, identifier: true }); if (name === 'browser.inspect_links' && own(args, 'limit')) boundedInteger(args.limit, 'limit', 1, MAX_LINKS); if (name === 'browser.follow_link') { boundedString(args.page_revision, 'page_revision', { min: 1, max: 128, identifier: true }); boundedString(args.link_id, 'link_id', { min: 1, max: 128, identifier: true }); } }
  return structuredClone(args);
}

function ipv4Private(value) {
  const octets = value.split('.').map(Number); if (octets.length !== 4 || octets.some(part => !Number.isInteger(part) || part < 0 || part > 255)) return true;
  const [a, b] = octets; return a === 0 || a === 10 || a === 127 || a === 169 && b === 254 || a === 172 && b >= 16 && b <= 31 || a === 192 && (b === 0 || b === 168) || a === 198 && (b === 18 || b === 19) || a >= 224 || a === 100 && b >= 64 && b <= 127;
}

function ipv6Private(value) {
  const normalized = value.toLowerCase().replace(/^\[|\]$/g, ''); if (!normalized || normalized === '::' || normalized === '::1') return true;
  if (normalized.startsWith('::ffff:')) return ipv4Private(normalized.slice(7));
  const groups = normalized.split('::'); if (groups.length > 2) return true; const left = groups[0] ? groups[0].split(':') : []; const right = groups[1] ? groups[1].split(':') : []; if ([...left, ...right].some(group => !/^[0-9a-f]{1,4}$/u.test(group))) return true; const count = left.length + right.length; if ((groups.length === 1 && count !== 8) || (groups.length === 2 && count >= 8)) return true;
  const first = Number.parseInt(left[0] ?? right[0] ?? '0', 16); const second = Number.parseInt(left[1] ?? right[1] ?? '0', 16); return (first & 0xfe00) === 0xfc00 || (first & 0xffc0) === 0xfe80 || (first & 0xff00) === 0xff00 || first === 0x2001 && second === 0xdb8;
}

function hostIsPrivate(host) { const value = host.replace(/^\[|\]$/g, '').toLowerCase(); const kind = isIP(value); return kind === 4 ? ipv4Private(value) : kind === 6 ? ipv6Private(value) : value === 'localhost' || value.endsWith('.localhost') || value.endsWith('.local') || value.endsWith('.internal') || value.endsWith('.lan') || value.endsWith('.home.arpa'); }

function checkUrlShape(raw) {
  if (typeof raw !== 'string' || Buffer.byteLength(raw, 'utf8') > MAX_URL) throw new ProviderToolError('provider_destination_rejected', 'URL exceeds bound');
  let url; try { url = new URL(raw); } catch { throw new ProviderToolError('provider_destination_rejected', 'URL is invalid'); }
  if (url.protocol !== 'https:' || url.username || url.password || url.hostname === '') throw new ProviderToolError('provider_destination_rejected', 'only public HTTPS URLs are accepted');
  if (url.port && url.port !== '443') throw new ProviderToolError('provider_destination_rejected', 'only HTTPS port 443 is accepted');
  return url;
}

async function publicAddress(host, resolve) {
  const value = host.replace(/^\[|\]$/g, ''); if (hostIsPrivate(value)) throw new ProviderToolError('provider_destination_rejected', 'private destination');
  if (isIP(value)) return value;
  let addresses; try { addresses = await resolve(value); } catch { throw new ProviderToolError('provider_destination_rejected', 'destination DNS unavailable'); }
  if (!Array.isArray(addresses) || addresses.length < 1 || addresses.length > 16) throw new ProviderToolError('provider_destination_rejected', 'destination DNS response invalid');
  const values = addresses.map(entry => typeof entry === 'string' ? entry : entry?.address); for (const address of values) if (typeof address !== 'string' || hostIsPrivate(address)) throw new ProviderToolError('provider_destination_rejected', 'destination resolves to a private address'); return values[0];
}
async function publicUrl(raw, resolve) {
  const url = checkUrlShape(raw); await publicAddress(url.hostname, resolve); return url;
}

function boundedText(value, max) { return typeof value === 'string' ? value.slice(0, max) : ''; }
async function killChild(child, killProcess, platform = process.platform) { if (!child) return; try { if (killProcess) await killProcess(child); else if (platform === 'win32' && Number.isInteger(child.pid)) await new Promise(resolve => { const killer = spawn('taskkill.exe', ['/PID', String(child.pid), '/T', '/F'], { shell: false, windowsHide: true, stdio: 'ignore' }); killer.once('close', resolve); killer.once('error', resolve); }); else if (Number.isInteger(child.pid) && process.platform !== 'win32') { try { process.kill(-child.pid, 'SIGTERM'); } catch { child.kill?.('SIGTERM'); } } else child.kill?.('SIGTERM'); } catch { /* cleanup is best effort */ } }
function ownTempDir(directory) { return typeof directory === 'string' && basename(directory).startsWith('lae-browser-') && dirname(directory) === tmpdir(); }
function withTimeout(task, signal, timeoutMs) { return new Promise((resolve, reject) => { let settled = false; const finish = (fn, value) => { if (settled) return; settled = true; clearTimeout(timer); signal?.removeEventListener('abort', abort); fn(value); }; const abort = () => finish(reject, new ProviderToolError('provider_cancelled')); const timer = setTimeout(() => finish(reject, new ProviderToolError('provider_timeout')), timeoutMs); signal?.addEventListener('abort', abort, { once: true }); Promise.resolve().then(task).then(value => finish(resolve, value), error => finish(reject, error)); }); }
async function readBoundedResponse(response, maxBytes) { const declared = Number(response.headers?.get?.('content-length') ?? 0); if (declared > maxBytes) throw new ProviderToolError('provider_response_too_large'); const reader = response.body?.getReader?.(); if (!reader) throw new ProviderToolError('provider_invalid_response'); const chunks = []; let total = 0; try { while (true) { const part = await reader.read(); if (part.done) break; const chunk = part.value instanceof Uint8Array ? part.value : new Uint8Array(part.value); total += chunk.byteLength; if (total > maxBytes) { await reader.cancel().catch(() => {}); throw new ProviderToolError('provider_response_too_large'); } chunks.push(chunk); } } finally { reader.releaseLock?.(); } const output = new Uint8Array(total); let offset = 0; for (const chunk of chunks) { output.set(chunk, offset); offset += chunk.byteLength; } return new TextDecoder('utf-8', { fatal: true }).decode(output); }

export class CdpClient {
  constructor({ port, resolve, fetchImpl = globalThis.fetch, WebSocketImpl = globalThis.WebSocket } = {}) { this.port = port; this.resolve = resolve; this.fetchImpl = fetchImpl; this.WebSocketImpl = WebSocketImpl; this.socket = null; this.nextId = 1; this.pending = new Map(); this.events = []; this.eventWaiters = []; }
  async connect(signal) {
    if (typeof this.fetchImpl !== 'function' || typeof this.WebSocketImpl !== 'function') throw new ProviderToolError('provider_unconfigured', 'CDP requires built-in fetch and WebSocket');
    const response = await this.fetchImpl(`http://127.0.0.1:${this.port}/json/list`, { signal }); if (!response.ok) throw new ProviderToolError('provider_unconfigured', 'CDP endpoint unavailable'); const raw = await readBoundedResponse(response, 65536); let targets; try { targets = JSON.parse(raw); } catch { throw new ProviderToolError('provider_invalid_response'); } const target = Array.isArray(targets) ? targets.slice(0, 16).find(item => item?.type === 'page' && typeof item.webSocketDebuggerUrl === 'string') : null; if (!target) throw new ProviderToolError('provider_unconfigured', 'CDP page target unavailable');
    const endpoint = new URL(target.webSocketDebuggerUrl); if (endpoint.protocol !== 'ws:' || endpoint.hostname !== '127.0.0.1' || endpoint.port !== String(this.port)) throw new ProviderToolError('provider_unconfigured', 'CDP target is not loopback bound');
    await new Promise((resolve, reject) => { const socket = new this.WebSocketImpl(endpoint.href); this.socket = socket; const fail = error => reject(error instanceof Error ? error : new Error('CDP connection failed')); socket.addEventListener('open', resolve, { once: true }); socket.addEventListener('error', fail, { once: true }); socket.addEventListener('close', () => { for (const item of this.pending.values()) item.reject(new ProviderToolError('provider_cancelled')); this.pending.clear(); }); socket.addEventListener('message', event => this.onMessage(typeof event.data === 'string' ? event.data : new TextDecoder().decode(event.data))); });
    await this.send('Page.enable', {}); await this.send('Network.enable', {}); await this.send('Fetch.enable', { patterns: [{ urlPattern: '*', requestStage: 'Request' }] });
  }
  onMessage(raw) { if (typeof raw !== 'string' || Buffer.byteLength(raw, 'utf8') > 262144) { this.close(); return; } let message; try { message = JSON.parse(raw); } catch { return; } if (message.id && this.pending.has(message.id)) { const item = this.pending.get(message.id); this.pending.delete(message.id); if (message.error) item.reject(new ProviderToolError('provider_failed', message.error.message ?? 'CDP command failed')); else item.resolve(message.result ?? {}); return; } if (message.method) { const index = this.eventWaiters.findIndex(item => item.method === message.method); if (index >= 0) this.eventWaiters.splice(index, 1)[0].resolve(message); else { if (this.events.length >= 128) this.events.shift(); this.events.push(message); } if (message.method === 'Fetch.requestPaused') this.guardRequest(message.params).catch(() => {}); } }
  async guardRequest(params) { const id = params?.requestId; const raw = params?.request?.url; if (typeof id !== 'string') return; try { await publicUrl(raw, this.resolve); await this.send('Fetch.continueRequest', { requestId: id }); } catch { await this.send('Fetch.failRequest', { requestId: id, errorReason: 'BlockedByClient' }).catch(() => {}); } }
  send(method, params) { if (!this.socket) return Promise.reject(new ProviderToolError('provider_unconfigured')); if (this.pending.size >= 64) return Promise.reject(new ProviderToolError('provider_response_too_large')); const id = this.nextId++; return new Promise((resolve, reject) => { this.pending.set(id, { resolve, reject }); try { this.socket.send(JSON.stringify({ id, method, params })); } catch (error) { this.pending.delete(id); reject(error); } }); }
  async waitLoad(signal) { const index = this.events.findIndex(event => event.method === 'Page.loadEventFired'); if (index >= 0) { this.events.splice(index, 1); return; } await withTimeout(() => new Promise((resolve, reject) => this.eventWaiters.push({ method: 'Page.loadEventFired', resolve, reject })), signal, REQUEST_TIMEOUT_MS); }
  async navigate(url, signal) { checkAborted(signal); await this.send('Page.navigate', { url: url.href }); await this.waitLoad(signal); checkAborted(signal); }
  async inspect(signal) { checkAborted(signal); const output = await this.send('Runtime.evaluate', { expression: PAGE_SCRIPT, returnByValue: true, awaitPromise: false }); const value = output?.result?.value; if (!value || typeof value !== 'object') throw new ProviderToolError('provider_invalid_response'); return value; }
  close() { try { this.socket?.close(); } catch { /* cleanup */ } this.socket = null; }
}

async function waitDevtoolsPort(directory, signal, timeoutMs) { const deadline = Date.now() + timeoutMs; while (Date.now() < deadline) { checkAborted(signal); try { const handle = await open(join(directory, 'DevToolsActivePort'), 'r'); const buffer = Buffer.alloc(1024); const { bytesRead } = await handle.read(buffer, 0, buffer.length, 0); await handle.close(); const lines = buffer.subarray(0, bytesRead).toString('utf8').split(/\r?\n/u); const port = Number(lines[0]); if (Number.isInteger(port) && port > 0 && port < 65536) return { port }; } catch { /* browser has not published its endpoint yet */ } await new Promise(resolve => setTimeout(resolve, 25)); } throw new ProviderToolError('provider_timeout', 'browser CDP endpoint did not start'); }

async function createValidatingProxy(resolve) { const sockets = new Set(); const server = createServer(socket => { if (sockets.size >= 32) return socket.end('HTTP/1.1 429 Too Many Requests\r\n\r\n'); sockets.add(socket); socket.once('close', () => sockets.delete(socket)); socket.setTimeout(5000, () => socket.destroy()); let data = ''; const onData = chunk => { data += chunk.toString('latin1'); if (Buffer.byteLength(data, 'latin1') > 8192) return socket.destroy(); const end = data.indexOf('\r\n\r\n'); if (end < 0) return; socket.off('data', onData); const line = data.slice(0, data.indexOf('\r\n')); const match = line.match(/^CONNECT\s+([^\s:]+|\[[^\]]+\]):(\d{1,5})\s+HTTP\/1\.1$/u); if (!match || match[2] !== '443') return socket.end('HTTP/1.1 403 Forbidden\r\n\r\n'); const host = match[1].replace(/^\[|\]$/g, ''); withTimeout(() => publicAddress(host, resolve), undefined, 5000).then(address => { const upstream = createConnection({ host: address, port: 443 }); sockets.add(upstream); upstream.once('close', () => sockets.delete(upstream)); upstream.setTimeout(5000, () => upstream.destroy()); upstream.once('connect', () => { socket.write('HTTP/1.1 200 Connection Established\r\n\r\n'); socket.pipe(upstream); upstream.pipe(socket); }); upstream.once('error', () => socket.destroy()); }).catch(() => socket.end('HTTP/1.1 403 Forbidden\r\n\r\n')); }; socket.on('data', onData); }); await new Promise((resolveListen, reject) => { server.once('error', reject); server.listen(0, '127.0.0.1', resolveListen); }); return { port: server.address().port, close: () => new Promise(resolveClose => { for (const socket of sockets) socket.destroy(); server.close(() => resolveClose()); }) }; }

export class BrowserActionProvider {
  constructor({ enabled = false, executable, allowlist = [], spawn: spawnImpl = spawn, killProcess, mkdtempImpl = mkdtemp, rmImpl = rm, proxyFactory = createValidatingProxy, waitDevtoolsPortImpl = waitDevtoolsPort, resolve = async host => (await dns.lookup(host, { all: true, verbatim: true })).map(item => item.address), cdpFactory, fetchImpl, WebSocketImpl, requestTimeoutMs = REQUEST_TIMEOUT_MS, platform = process.platform } = {}) {
    if (!Array.isArray(allowlist) || allowlist.length > 16 || allowlist.some(item => typeof item !== 'string' || item.length < 1 || item.length > 1024)) throw new TypeError('invalid browser allowlist');
    if (!Number.isInteger(requestTimeoutMs) || requestTimeoutMs < 100 || requestTimeoutMs > 120000) throw new TypeError('invalid browser timeout');
    this.enabled = enabled === true; this.executable = executable; this.allowlist = new Set(allowlist); this.spawn = spawnImpl; this.killProcess = killProcess; this.mkdtemp = mkdtempImpl; this.rm = rmImpl; this.proxyFactory = proxyFactory; this.waitDevtoolsPort = waitDevtoolsPortImpl; this.resolve = resolve; this.cdpFactory = cdpFactory; this.fetchImpl = fetchImpl; this.WebSocketImpl = WebSocketImpl; this.requestTimeoutMs = requestTimeoutMs; this.platform = platform; this.sessions = new Map(); this.proposals = new Map();
  }
  state() { if (!this.enabled) return 'disabled'; if (typeof this.executable !== 'string' || !this.executable || !this.allowlist.has(this.executable)) return 'unconfigured'; return 'unverified'; }
  async destination(raw) { return publicUrl(raw, this.resolve); }
  remember(call, args) { if (this.proposals.size >= 128 && !this.proposals.has(call.id)) this.proposals.delete(this.proposals.keys().next().value); this.proposals.set(call.id, { name: call.name, digest: digest(args) }); }
  assertProposal(call, args) { const saved = this.proposals.get(call.id); if (!saved || saved.name !== call.name || saved.digest !== digest(args)) throw new ProviderToolError('provider_permission_insufficient', 'browser action requires a matching preview'); }
  async preview(call) { const args = validate(call.name, call.arguments); if (call.name === 'browser.session_start') { const url = await this.destination(args.url); this.remember(call, args); return { provider: 'browser_actions', action: 'session_start', destination: url.href, data_egress: 'external_destination' }; } if (call.name === 'browser.follow_link') { const session = this.sessions.get(args.browser_session_id); if (!session || session.closed) throw new ProviderToolError('browser_session_stale'); if (session.revision !== args.page_revision) throw new ProviderToolError('browser_session_stale'); const link = session.links.get(args.link_id); if (!link) throw new ProviderToolError('browser_link_changed'); await this.destination(link.url); this.remember(call, args); return { provider: 'browser_actions', action: 'follow_link', browser_session_id: session.id, page_revision: session.revision, link_id: link.id, destination: link.url, data_egress: 'external_destination' }; } return { provider: 'browser_actions', action: call.name, browser_session_id: args.browser_session_id }; }
  async authorize(call) { validate(call.name, call.arguments); if (call.name === 'browser.session_start' || call.name === 'browser.follow_link') return { kind: 'policy' }; return { kind: 'policy' }; }
  async execute(call) { try { const args = validate(call.name, call.arguments); return await this._execute(call, args); } catch (error) { if (error?.code === 'invalid_tool_arguments') throw error; return failureResult(call, error); } }
  async _execute(call, args) {
    checkAborted(call.signal); if (this.state() === 'disabled') return failureResult(call, new ProviderToolError('provider_disabled')); if (this.state() === 'unconfigured') return failureResult(call, new ProviderToolError('provider_unconfigured'));
    if (call.name === 'browser.session_close') return this.closeSession(call, args);
    if (call.name === 'browser.inspect_links') return this.inspectLinks(call, args);
    if (call.name === 'browser.session_start') { if (call.authorization?.kind !== 'user_confirmation') return failureResult(call, new ProviderToolError('provider_permission_insufficient')); this.assertProposal(call, args); return this.startSession(call, args); }
    if (call.name === 'browser.follow_link') { if (call.authorization?.kind !== 'user_confirmation') return failureResult(call, new ProviderToolError('provider_permission_insufficient')); this.assertProposal(call, args); return this.followLink(call, args); }
    throw new ProviderToolError('invalid_tool_arguments');
  }
  async startSession(call, args) {
    const url = await this.destination(args.url); const directory = await this.mkdtemp(join(tmpdir(), 'lae-browser-')); if (!ownTempDir(directory)) throw new ProviderToolError('provider_failed', 'temporary profile path is not owned');
    let child; let cdp; let proxy; try {
      proxy = await withTimeout(() => this.proxyFactory(this.resolve), call.signal, this.requestTimeoutMs); if (!proxy || !Number.isInteger(proxy.port) || proxy.port < 1 || proxy.port > 65535) throw new ProviderToolError('provider_failed', 'browser proxy did not start'); const argv = [`--user-data-dir=${directory}`, '--no-first-run', '--no-default-browser-check', '--disable-extensions', '--disable-sync', '--disable-background-networking', '--proxy-bypass-list=<-loopback>', `--proxy-server=http://127.0.0.1:${proxy.port}`, '--remote-debugging-address=127.0.0.1', '--remote-debugging-port=0']; child = this.spawn(this.executable, argv, { shell: false, windowsHide: true, detached: this.platform !== 'win32', stdio: 'ignore' }); if (!child || typeof child.once !== 'function') throw new ProviderToolError('provider_failed', 'browser process did not start'); const devtools = await withTimeout(() => this.waitDevtoolsPort(directory, call.signal, this.requestTimeoutMs), call.signal, this.requestTimeoutMs); cdp = this.cdpFactory ? await this.cdpFactory({ port: devtools.port, resolve: this.resolve, fetchImpl: this.fetchImpl, WebSocketImpl: this.WebSocketImpl, signal: call.signal }) : new CdpClient({ port: devtools.port, resolve: this.resolve, fetchImpl: this.fetchImpl, WebSocketImpl: this.WebSocketImpl }); await withTimeout(() => cdp.connect(call.signal), call.signal, this.requestTimeoutMs); await withTimeout(() => cdp.navigate(url, call.signal), call.signal, this.requestTimeoutMs); const page = await withTimeout(() => cdp.inspect(call.signal), call.signal, this.requestTimeoutMs); await this.destination(page.url); const session = await this.recordSession({ directory, child, cdp, proxy, url, page }); this.proposals.delete(call.id); return result(call, 'ok', { provider: 'browser_actions', state: 'ready', browser_session_id: session.id, url: session.url, title: session.title, page_revision: session.revision });
    } catch (error) { cdp?.close?.(); await killChild(child, this.killProcess, this.platform); await proxy?.close?.(); await this.removeDirectory(directory); throw error; }
  }
  async recordSession({ directory, child, cdp, proxy, url, page }) { const id = `browser_${randomUUID().replaceAll('-', '')}`; const session = { id, directory, child, cdp, proxy, url: url.href, title: boundedText(page.title, MAX_PAGE_TITLE), revision: '', links: new Map(), closed: false }; this.updatePage(session, page); if (this.sessions.size >= MAX_SESSIONS) { const oldest = this.sessions.keys().next().value; await this.closeStored(this.sessions.get(oldest)); this.sessions.delete(oldest); } this.sessions.set(id, session); child.once('exit', () => { if (!session.closed) { session.closed = true; cdp?.close?.(); void proxy?.close?.(); void this.removeDirectory(directory); } }); return session; }
  updatePage(session, page) { const current = checkUrlShape(page.url); session.url = current.href; session.title = boundedText(page.title, MAX_PAGE_TITLE); session.links = new Map(); const links = Array.isArray(page.links) ? page.links.slice(0, MAX_LINK_SCAN) : []; for (let index = 0; index < links.length && session.links.size < MAX_LINKS; index++) { const candidate = links[index]; if (!candidate || typeof candidate !== 'object' || typeof candidate.href !== 'string') continue; let target; try { target = checkUrlShape(candidate.href); } catch { continue; } const id = `link_${digest({ revision: session.revision, index, url: target.href }).slice(0, 24)}`; session.links.set(id, { id, url: target.href, label: boundedText(candidate.label, MAX_LABEL) }); } session.revision = digest({ url: session.url, title: session.title, links: [...session.links.values()] }); return session; }
  async inspectLinks(call, args) { const session = this.sessions.get(args.browser_session_id); if (!session || session.closed) return failureResult(call, new ProviderToolError('browser_session_stale')); const page = await withTimeout(() => session.cdp.inspect(call.signal), call.signal, this.requestTimeoutMs); const before = session.revision; const current = await this.destination(page.url); if (current.href !== page.url) throw new ProviderToolError('browser_session_stale'); this.updatePage(session, page); const links = [...session.links.values()].slice(0, args.limit ?? MAX_LINKS); return result(call, 'ok', { provider: 'browser_actions', state: 'ready', browser_session_id: session.id, url: session.url, title: session.title, page_revision: session.revision, links, truncated: session.links.size > links.length || before !== session.revision }); }
  async followLink(call, args) { const session = this.sessions.get(args.browser_session_id); if (!session || session.closed) return failureResult(call, new ProviderToolError('browser_session_stale')); if (session.revision !== args.page_revision) return failureResult(call, new ProviderToolError('browser_session_stale')); const link = session.links.get(args.link_id); if (!link) return failureResult(call, new ProviderToolError('browser_link_changed')); const destination = await this.destination(link.url); try { await withTimeout(() => session.cdp.navigate(destination, call.signal), call.signal, this.requestTimeoutMs); const page = await withTimeout(() => session.cdp.inspect(call.signal), call.signal, this.requestTimeoutMs); await this.destination(page.url); this.updatePage(session, page); this.proposals.delete(call.id); return result(call, 'ok', { provider: 'browser_actions', state: 'ready', browser_session_id: session.id, url: session.url, title: session.title, page_revision: session.revision, followed_link_id: link.id }); } catch (error) { if (error?.code === 'provider_destination_rejected') return failureResult(call, error); throw error; } }
  async closeSession(call, args) { const session = this.sessions.get(args.browser_session_id); if (!session || session.closed) return failureResult(call, new ProviderToolError('browser_session_stale')); await this.closeStored(session); this.sessions.delete(session.id); return result(call, 'ok', { provider: 'browser_actions', state: 'closed', browser_session_id: session.id, closed: true }); }
  async closeStored(session) { if (!session || session.closed) return; session.closed = true; session.cdp?.close?.(); await killChild(session.child, this.killProcess, this.platform); await session.proxy?.close?.(); await this.removeDirectory(session.directory); }
  async removeDirectory(directory) { if (!ownTempDir(directory)) return; try { await this.rm(directory, { recursive: true, force: true }); } catch { /* cleanup remains best effort and never broadens the target */ } }
  async shutdown() { await Promise.all([...this.sessions.values()].map(session => this.closeStored(session))); this.sessions.clear(); }
}

export function createBrowserActionTools(options = {}) { const provider = options instanceof BrowserActionProvider ? options : new BrowserActionProvider(options); return Object.fromEntries(Object.entries(definitions).map(([name, definition]) => [name, { ...definition, confirmationRequired: () => definition.requires_confirmation, authorize: call => provider.authorize({ ...call, name }), preview: call => provider.preview({ ...call, name }), execute: call => provider.execute({ ...call, name }) }])); }

export { browserSchemas, definitions as browserActionDefinitions, publicAddress, publicUrl, hostIsPrivate };
