import { spawn as nodeSpawn } from 'node:child_process';
import { ProviderToolError, boundedArray, boundedString, checkAborted, digest, exactObject, failureResult, result } from './provider-common.mjs';

const MAX_OUTPUT = 65536;
const PATH = (value, name = 'context_path') => boundedString(value, name, { min: 1, max: 1024, identifier: true }).replaceAll('\\', '/');
const validate = input => { const args = exactObject(input, ['prompt', 'workspace_id', 'context_paths'], ['prompt', 'workspace_id', 'context_paths']); boundedString(args.prompt, 'prompt', { min: 1, max: 8192 }); boundedString(args.workspace_id, 'workspace_id', { min: 1, max: 64, identifier: true }); boundedArray(args.context_paths, 'context_paths', { max: 8 }); const contextPaths = args.context_paths.map((value, index) => PATH(value, `context_paths[${index}]`)); if (contextPaths.some(value => value.startsWith('/') || /^[A-Za-z]:\//u.test(value) || value.split('/').some(part => !part || part === '.' || part === '..'))) throw new ProviderToolError('invalid_tool_arguments', 'context paths must be relative and contained'); return { ...structuredClone(args), context_paths: contextPaths }; };

const COPILOT_PARAMETERS = { type: 'object', additionalProperties: false, required: ['prompt', 'workspace_id', 'context_paths'], properties: { prompt: { type: 'string', minLength: 1, maxLength: 8192 }, workspace_id: { type: 'string', minLength: 1, maxLength: 64 }, context_paths: { type: 'array', maxItems: 8, items: { type: 'string', minLength: 1, maxLength: 1024 } } } };
export const copilotDefinition = Object.freeze({ name: 'coding.copilot_ask', version: '0.1.0', description: 'Ask GitHub Copilot for a bounded prompt-only answer with explicitly selected context.', risk_tier: 'T3', side_effect: 'cloud_inference', network: true, data_egress: 'prompt_and_selected_files', requires_confirmation: true, timeout_ms: 30000, output_limit: MAX_OUTPUT, parameters: COPILOT_PARAMETERS, input_schema: COPILOT_PARAMETERS });

function spawnProcess(executable, args, options) { return nodeSpawn(executable, args, options); }

export class CopilotCliProvider {
  constructor({ enabled = false, executable, allowlist = [], version = 'unverified', versionCheck, readContext, spawn = spawnProcess, killProcess, timeoutMs = 30000, maxOutput = MAX_OUTPUT, environment = process.env } = {}) {
    this.enabled = enabled === true; this.executable = executable; this.allowlist = new Set(allowlist); this.version = version; this.versionCheck = versionCheck; this.readContext = readContext; this.spawn = spawn; this.killProcess = killProcess ?? (child => child.kill('SIGTERM')); this.timeoutMs = Math.min(120000, Math.max(100, timeoutMs)); this.maxOutput = Math.min(MAX_OUTPUT, Math.max(1024, maxOutput)); this.environment = environment; this.proposals = new Map();
  }
  state() { if (!this.enabled) return 'disabled'; if (typeof this.executable !== 'string' || !this.executable || !this.versionCheck) return 'unconfigured'; if (!this.allowlist.has(this.executable)) return 'unconfigured'; return 'ready'; }
  validate(input) { return validate(input); }
  async preview(call) { const args = validate(call.arguments); const context = await this.context(args); const contextBytes = Buffer.byteLength(context, 'utf8'); const promptBytes = Buffer.byteLength(args.prompt, 'utf8'); const separatorBytes = context ? Buffer.byteLength('\n\nSelected context:\n', 'utf8') : 0; const bytes = promptBytes + separatorBytes + contextBytes; if (bytes > 65536) throw new ProviderToolError('invalid_tool_arguments', 'prompt and selected context exceed egress bound'); const proposal = { digest: digest(args), name: call.name, workspace_id: args.workspace_id, context_digest: digest(context), context_bytes: contextBytes, egress_bytes: bytes }; if (this.proposals.size >= 128) this.proposals.delete(this.proposals.keys().next().value); this.proposals.set(call.id, proposal); return { provider: 'github_copilot', destination: 'GitHub Copilot cloud', action: 'prompt_only', workspace_id: args.workspace_id, context_paths: args.context_paths, egress_bytes: bytes, data_categories: ['prompt', ...(args.context_paths.length ? ['selected_workspace_files'] : [])], disclosure: 'Selected prompt/context is sent to GitHub Copilot; output is untrusted.' }; }
  async execute(call) {
    let args; try { args = validate(call.arguments); const saved = this.proposals.get(call.id); if (!saved || saved.digest !== digest(args)) throw new ProviderToolError('copilot_policy_denied'); if (!call.authorization || typeof call.authorization !== 'object' || Array.isArray(call.authorization) || call.authorization.kind !== 'user_confirmation' || Object.keys(call.authorization).length !== 1) throw new ProviderToolError('provider_permission_insufficient'); if (!this.enabled) throw new ProviderToolError('copilot_cli_unavailable'); if (!this.executable || !this.versionCheck || !this.allowlist.has(this.executable)) throw new ProviderToolError('copilot_policy_denied'); if (!await this.versionCheck(this.executable)) throw new ProviderToolError('copilot_policy_denied'); const context = await this.context(args); const contextBytes = Buffer.byteLength(context, 'utf8'); if (digest(context) !== saved.context_digest || contextBytes !== saved.context_bytes) throw new ProviderToolError('copilot_policy_denied', 'selected context changed after preview'); const prompt = context ? `${args.prompt}\n\nSelected context:\n${context}` : args.prompt; if (Buffer.byteLength(prompt, 'utf8') !== saved.egress_bytes || Buffer.byteLength(prompt, 'utf8') > 65536) throw new ProviderToolError('copilot_policy_denied'); return await this.run(call, args, prompt); } catch (error) { if (error?.code === 'invalid_tool_arguments') throw error; return failureResult(call, error); }
  }
  async context(args) {
    if (!args.context_paths.length) return '';
    if (typeof this.readContext !== 'function') throw new ProviderToolError('copilot_policy_denied');
    const value = await this.readContext(args.workspace_id, args.context_paths); if (typeof value !== 'string' || Buffer.byteLength(value, 'utf8') > 57344) throw new ProviderToolError('provider_response_too_large'); return value;
  }
  async run(call, args, prompt) {
    checkAborted(call.signal); const started = Date.now(); const child = this.spawn(this.executable, ['-s', '--no-auto-update', '--no-custom-instructions', '--no-remote', '--no-remote-export', '--no-ask-user', '--disable-builtin-mcps', '--available-tools='], { shell: false, windowsHide: true, stdio: ['pipe', 'pipe', 'pipe'], env: this.safeEnvironment() }); let output = ''; let truncated = false; let stderr = ''; const outputDecoder = new TextDecoder(); const stderrDecoder = new TextDecoder();
    const collect = (current, chunk, decoder, final = false) => { const bytes = Buffer.isBuffer(chunk) ? chunk : Buffer.from(String(chunk), 'utf8'); const text = decoder.decode(bytes, { stream: !final }); const room = this.maxOutput - Buffer.byteLength(current, 'utf8'); if (room <= 0) { truncated = true; return current; } const textBytes = Buffer.from(text, 'utf8'); if (textBytes.length > room) { truncated = true; let bounded = new TextDecoder().decode(textBytes.subarray(0, room)); while (bounded.endsWith('\uFFFD')) bounded = bounded.slice(0, -1); return current + bounded; } return current + text; };
    const stop = () => { try { this.killProcess(child); } catch {} };
    let outputOverflow = false;
    return await new Promise((resolve) => {
      let settled = false; const finish = value => { if (!settled) { settled = true; clearTimeout(timer); call.signal?.removeEventListener('abort', abort); resolve(value); } }; const abort = () => { stop(); finish(failureResult(call, new ProviderToolError('provider_cancelled'))); }; const timer = setTimeout(() => { stop(); finish(failureResult(call, new ProviderToolError('provider_timeout'))); }, this.timeoutMs);
      child.stdout?.on('data', chunk => { const before = Buffer.byteLength(output, 'utf8'); output = collect(output, chunk, outputDecoder); if (Buffer.byteLength(output, 'utf8') >= this.maxOutput && Buffer.byteLength(chunk) + before > this.maxOutput && !outputOverflow) { outputOverflow = true; stop(); } }); child.stderr?.on('data', chunk => { stderr = collect(stderr, chunk, stderrDecoder); }); child.once('error', error => finish(failureResult(call, new ProviderToolError(error.code === 'ENOENT' ? 'copilot_cli_unavailable' : 'provider_failed')))); child.once('close', code => { output = collect(output, Buffer.alloc(0), outputDecoder, true); const exitClass = code === 0 ? 'ok' : code === null ? 'cancelled' : 'failed'; finish(result(call, code === 0 ? 'ok' : 'failed', { provider: 'github_copilot', state: 'ready', stdout: output, exit_class: exitClass, truncated, duration_ms: Date.now() - started, cli_version: this.version, egress_bytes: Buffer.byteLength(prompt, 'utf8') })); }); call.signal?.addEventListener('abort', abort, { once: true }); child.stdin?.end(prompt, 'utf8');
    });
  }
  safeEnvironment() { const env = {}; if (typeof this.environment?.PATH === 'string') env.PATH = this.environment.PATH; if (typeof this.environment?.SystemRoot === 'string') env.SystemRoot = this.environment.SystemRoot; if (typeof this.environment?.COPILOT_HOME === 'string') env.COPILOT_HOME = this.environment.COPILOT_HOME; if (typeof this.environment?.COPILOT_GH_HOST === 'string') env.COPILOT_GH_HOST = this.environment.COPILOT_GH_HOST; return env; }
}

export function createCopilotTool(options = {}) { const provider = options instanceof CopilotCliProvider ? options : new CopilotCliProvider(options); return { ...copilotDefinition, preview: call => provider.preview(call), execute: call => provider.execute(call) }; }
