import { createMicrosoftGraphTools, MicrosoftGraphProvider, graphDefinitions } from './microsoft-graph.mjs';
import { createCopilotTool, CopilotCliProvider, copilotDefinition } from './copilot-cli.mjs';
import { OperatorGrantStore, PERMISSION_PROFILES } from './operator-grants.mjs';

function exactOptions(value, allowed, name) { if (value === undefined) return {}; if (!value || typeof value !== 'object' || Array.isArray(value)) throw new TypeError(`${name} must be an object`); for (const key of Object.keys(value)) if (!allowed.includes(key)) throw new TypeError(`${name} has unknown option: ${key}`); return value; }

export function createExternalToolRegistry({ graph, copilot, config = {} } = {}) {
  const safeConfig = exactOptions(config, ['microsoft_graph', 'copilot'], 'provider config'); const graphConfig = exactOptions(safeConfig.microsoft_graph, ['enabled', 'permission_profile', 'account_fingerprint', 'scope'], 'microsoft_graph config'); const copilotConfig = exactOptions(safeConfig.copilot, ['enabled', 'executable', 'allowlist', 'version'], 'copilot config');
  const graphInjection = graph instanceof MicrosoftGraphProvider ? {} : exactOptions(graph, ['enabled', 'credentialSource', 'transport', 'origin', 'permissionProfile', 'grantStore', 'accountFingerprint', 'scope', 'now', 'requestTimeoutMs'], 'Graph injection'); const copilotInjection = copilot instanceof CopilotCliProvider ? {} : exactOptions(copilot, ['enabled', 'executable', 'allowlist', 'version', 'versionCheck', 'readContext', 'spawn', 'killProcess', 'timeoutMs', 'maxOutput', 'environment'], 'Copilot injection');
  const graphProvider = graph instanceof MicrosoftGraphProvider ? graph : new MicrosoftGraphProvider({ enabled: graphInjection.enabled ?? graphConfig.enabled ?? false, permissionProfile: graphInjection.permissionProfile ?? graphConfig.permission_profile ?? 'always_ask', accountFingerprint: graphInjection.accountFingerprint ?? graphConfig.account_fingerprint ?? 'unknown', scope: graphInjection.scope ?? graphConfig.scope ?? 'account', credentialSource: graphInjection.credentialSource, transport: graphInjection.transport, origin: graphInjection.origin, grantStore: graphInjection.grantStore, now: graphInjection.now, requestTimeoutMs: graphInjection.requestTimeoutMs });
  const copilotProvider = copilot instanceof CopilotCliProvider ? copilot : new CopilotCliProvider({ enabled: copilotInjection.enabled ?? copilotConfig.enabled ?? false, executable: copilotInjection.executable ?? copilotConfig.executable, allowlist: copilotInjection.allowlist ?? copilotConfig.allowlist ?? [], version: copilotInjection.version ?? copilotConfig.version ?? 'unverified', versionCheck: copilotInjection.versionCheck, readContext: copilotInjection.readContext, spawn: copilotInjection.spawn, killProcess: copilotInjection.killProcess, timeoutMs: copilotInjection.timeoutMs, maxOutput: copilotInjection.maxOutput, environment: copilotInjection.environment });
  const registry = { ...createMicrosoftGraphTools(graphProvider), [copilotDefinition.name]: createCopilotTool(copilotProvider) }; Object.defineProperty(registry, 'providerStatus', { enumerable: false, value: () => ({ microsoft_graph: graphProvider.state(), copilot: copilotProvider.state() }) }); return registry;
}

export { CopilotCliProvider, MicrosoftGraphProvider, OperatorGrantStore, PERMISSION_PROFILES, copilotDefinition, graphDefinitions };
