import { createMicrosoftGraphTools, MicrosoftGraphProvider, graphDefinitions } from './microsoft-graph.mjs';
import { createCopilotTool, createCopilotVersionCheck, CopilotCliProvider, copilotDefinition } from './copilot-cli.mjs';
import { MicrosoftDeviceCodeCredential, MicrosoftGraphHttpsTransport } from './microsoft-graph-auth.mjs';
import { OperatorGrantStore, OperatorGrantControl, buildOperatorGrantBindings, PERMISSION_PROFILES } from './operator-grants.mjs';
import { createBrowserActionTools, BrowserActionProvider, browserActionDefinitions } from './browser-actions.mjs';
import { createWorkspaceContextReader } from './copilot-context.mjs';

function exactOptions(value, allowed, name) { if (value === undefined) return {}; if (!value || typeof value !== 'object' || Array.isArray(value)) throw new TypeError(`${name} must be an object`); for (const key of Object.keys(value)) if (!allowed.includes(key)) throw new TypeError(`${name} has unknown option: ${key}`); return value; }

export function createExternalToolRegistry({ graph, copilot, browser, config = {}, workspaceRoots } = {}) {
  const safeConfig = exactOptions(config, ['microsoft_graph', 'copilot', 'browser_actions'], 'provider config'); const graphConfig = exactOptions(safeConfig.microsoft_graph, ['enabled', 'permission_profile', 'account_fingerprint', 'scope', 'tenant', 'client_id', 'scopes'], 'microsoft_graph config'); const copilotConfig = exactOptions(safeConfig.copilot, ['enabled', 'executable', 'allowlist', 'version'], 'copilot config'); const browserConfig = exactOptions(safeConfig.browser_actions, ['enabled', 'executable', 'allowlist'], 'browser_actions config');
  const graphInjection = graph instanceof MicrosoftGraphProvider ? {} : exactOptions(graph, ['enabled', 'credentialSource', 'transport', 'authTransport', 'origin', 'permissionProfile', 'accountFingerprint', 'scope', 'tenant', 'clientId', 'scopes', 'onUserCode', 'sleep', 'now', 'requestTimeoutMs', 'grantStore', 'testOnly'], 'Graph injection'); const copilotInjection = copilot instanceof CopilotCliProvider ? {} : exactOptions(copilot, ['enabled', 'executable', 'allowlist', 'version', 'versionCheck', 'readContext', 'spawn', 'killProcess', 'timeoutMs', 'maxOutput', 'environment', 'platform', 'testOnly'], 'Copilot injection'); if (copilotInjection.readContext !== undefined && copilotInjection.testOnly !== true) throw new TypeError('Copilot readContext injection is test-only'); const browserInjection = browser instanceof BrowserActionProvider ? {} : exactOptions(browser, ['enabled', 'executable', 'allowlist', 'spawn', 'killProcess', 'mkdtempImpl', 'rmImpl', 'proxyFactory', 'waitDevtoolsPortImpl', 'resolve', 'cdpFactory', 'fetchImpl', 'WebSocketImpl', 'requestTimeoutMs', 'platform'], 'Browser injection');
  const graphProvider = graph instanceof MicrosoftGraphProvider ? graph : new MicrosoftGraphProvider({ enabled: graphInjection.enabled ?? graphConfig.enabled ?? false, permissionProfile: graphInjection.permissionProfile ?? graphConfig.permission_profile ?? 'always_ask', accountFingerprint: graphInjection.accountFingerprint ?? graphConfig.account_fingerprint ?? 'unknown', scope: graphInjection.scope ?? graphConfig.scope ?? 'account', tenant: graphInjection.tenant ?? graphConfig.tenant, clientId: graphInjection.clientId ?? graphConfig.client_id, scopes: graphInjection.scopes ?? graphConfig.scopes, credentialSource: graphInjection.credentialSource, transport: graphInjection.transport, authTransport: graphInjection.authTransport, origin: graphInjection.origin, grantStore: graphInjection.grantStore, now: graphInjection.now, sleep: graphInjection.sleep, onUserCode: graphInjection.onUserCode, requestTimeoutMs: graphInjection.requestTimeoutMs, testOnly: graphInjection.testOnly });
  const copilotExecutable = copilotInjection.executable ?? copilotConfig.executable; const copilotVersion = copilotInjection.version ?? copilotConfig.version ?? 'unverified'; const copilotEnvironment = copilotInjection.environment; const productionVersionCheck = !copilotInjection.spawn && !copilotInjection.versionCheck && copilotExecutable && copilotVersion !== 'unverified' ? createCopilotVersionCheck({ expectedVersion: copilotVersion, environment: copilotEnvironment }) : undefined;
  const workspaceContext = workspaceRoots === undefined ? undefined : createWorkspaceContextReader(workspaceRoots);
  const copilotProvider = copilot instanceof CopilotCliProvider ? copilot : new CopilotCliProvider({ enabled: copilotInjection.enabled ?? copilotConfig.enabled ?? false, executable: copilotExecutable, allowlist: copilotInjection.allowlist ?? copilotConfig.allowlist ?? [], version: copilotVersion, versionCheck: copilotInjection.versionCheck ?? productionVersionCheck, protocol: copilotInjection.spawn ? 'legacy_stdin' : 'acp', readContext: workspaceContext ?? (copilotInjection.testOnly === true ? copilotInjection.readContext : undefined), spawn: copilotInjection.spawn, killProcess: copilotInjection.killProcess, timeoutMs: copilotInjection.timeoutMs, maxOutput: copilotInjection.maxOutput, environment: copilotEnvironment, platform: copilotInjection.platform });
  const browserProvider = browser instanceof BrowserActionProvider ? browser : new BrowserActionProvider({ enabled: browserInjection.enabled ?? browserConfig.enabled ?? false, executable: browserInjection.executable ?? browserConfig.executable, allowlist: browserInjection.allowlist ?? browserConfig.allowlist ?? [], spawn: browserInjection.spawn, killProcess: browserInjection.killProcess, mkdtempImpl: browserInjection.mkdtempImpl, rmImpl: browserInjection.rmImpl, proxyFactory: browserInjection.proxyFactory, waitDevtoolsPortImpl: browserInjection.waitDevtoolsPortImpl, resolve: browserInjection.resolve, cdpFactory: browserInjection.cdpFactory, fetchImpl: browserInjection.fetchImpl, WebSocketImpl: browserInjection.WebSocketImpl, requestTimeoutMs: browserInjection.requestTimeoutMs, platform: browserInjection.platform });
  const registry = { ...createMicrosoftGraphTools(graphProvider), [copilotDefinition.name]: createCopilotTool(copilotProvider), ...createBrowserActionTools(browserProvider) }; Object.defineProperty(registry, 'providerStatus', { enumerable: false, value: () => ({ microsoft_graph: graphProvider.state(), copilot: copilotProvider.state(), browser_actions: browserProvider.state() }) }); Object.defineProperty(registry, 'providerAuthStatus', { enumerable: false, value: () => ({ microsoft_graph: graphProvider.authStatus() }) }); Object.defineProperty(registry, 'providerAuthControl', { enumerable: false, value: () => ({ microsoft_graph: { configured: graphProvider.authConfigured(), start: signal => graphProvider.startAuth(signal), status: () => graphProvider.authStatus(), cancel: () => graphProvider.cancelAuth(), clear: () => graphProvider.clearAuth() } }) }); let shutdownPromise; Object.defineProperty(registry, 'shutdown', { enumerable: false, value: () => shutdownPromise ??= (async () => { graphProvider.cancelAuth(); graphProvider.clearAuth(); await browserProvider.shutdown(); })() }); return registry;
}

export { BrowserActionProvider, CopilotCliProvider, createCopilotVersionCheck, MicrosoftGraphProvider, MicrosoftDeviceCodeCredential, MicrosoftGraphHttpsTransport, OperatorGrantStore, OperatorGrantControl, buildOperatorGrantBindings, PERMISSION_PROFILES, browserActionDefinitions, copilotDefinition, graphDefinitions };
