import test from 'node:test';
import assert from 'node:assert/strict';
import { EventEmitter } from 'node:events';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { mkdtemp, readFile } from 'node:fs/promises';
import { createExternalToolRegistry } from '../../host/providers/index.mjs';
import { BrowserActionProvider, CdpClient, createBrowserActionTools, publicAddress, publicUrl } from '../../host/providers/browser-actions.mjs';
import { MicrosoftGraphProvider, createMicrosoftGraphTools } from '../../host/providers/microsoft-graph.mjs';
import { CopilotCliProvider, createCopilotTool, createCopilotVersionCheck, killCopilotProcessTree } from '../../host/providers/copilot-cli.mjs';
import { OperatorGrantStore } from '../../host/providers/operator-grants.mjs';
import { ConversationController } from '../../host/agent/controller.mjs';
import { mergeConfig, validateConfig } from '../../host/agent/config.mjs';

const call = (name, arguments_, id = `call_${name.replaceAll('.', '_')}`) => ({ id, name, arguments: arguments_ });
const value = result => JSON.parse(result.content[0].text);
const revision = 'a'.repeat(64);

test('external contract publishes complete strict schemas for every tool', async () => {
  const contract = JSON.parse(await readFile(new URL('../../contracts/external-tools/v0.1.0.json', import.meta.url), 'utf8'));
  assert.equal(contract.version, '0.1.0'); assert.equal(contract.additionalProperties, false);
  assert.equal(new Set(contract.tools.map(tool => tool.name)).size, 13);
  const riskTiers = new Set(contract.$defs.tool.properties.risk_tier.enum); for (const tool of contract.tools) { assert.ok(riskTiers.has(tool.risk_tier), `${tool.name} uses an undeclared risk tier`); assert.equal(tool.input_schema.type, 'object'); assert.equal(tool.input_schema.additionalProperties, false); assert.ok(typeof tool.input_schema.properties === 'object'); } for (const name of ['browser.session_start', 'browser.inspect_links', 'browser.follow_link', 'browser.session_close']) { const definition = createExternalToolRegistry()[name]; assert.equal(definition.parameters.additionalProperties, false); assert.ok(definition.description); }
});

test('Graph provider is disabled/auth typed and rejects unknown or oversized arguments', async () => {
  const tools = createMicrosoftGraphTools(); const disabled = value(await tools['mail.list_messages'].execute(call('mail.list_messages', {}))); assert.equal(disabled.code, 'provider_disabled');
  const names = ['mail.list_messages', 'mail.read_message', 'mail.create_draft', 'mail.send_draft', 'mail.mark_read', 'teams.list_chats', 'teams.list_messages', 'teams.send_message'];
  for (const name of names) assert.equal(tools[name].input_schema.additionalProperties, false);
  for (const name of names) await assert.rejects(() => tools[name].execute(call(name, { unknown: true })), error => error.code === 'invalid_tool_arguments');
  await assert.rejects(() => tools['mail.create_draft'].execute(call('mail.create_draft', { to: ['not-an-address'], subject: 'x', body: 'x' })), error => error.code === 'invalid_tool_arguments');
  const unauthorized = createMicrosoftGraphTools({ enabled: true, credentialSource: { getAccessToken: async () => { throw new Error('no account'); } }, transport: { request: async () => ({ status: 200, body: {} }) } });
  const authResult = value(await unauthorized['mail.list_messages'].execute(call('mail.list_messages', {}))); assert.equal(authResult.code, 'provider_unauthorized');
  const offline = createMicrosoftGraphTools({ enabled: true, credentialSource: { getAccessToken: async () => 'synthetic-token' }, transport: { request: async () => { throw Object.assign(new Error('offline'), { code: 'offline' }); } } }); const offlineResult = value(await offline['mail.list_messages'].execute(call('mail.list_messages', {}))); assert.equal(offlineResult.code, 'provider_offline');
});

test('Graph fake transport receives fixed /me endpoints and bounded projections', async () => {
  const requests = []; const transport = { request: async request => { requests.push(request); if (request.path.includes('/messages/') && request.method === 'GET') return { status: 200, body: { id: 'm-1', receivedDateTime: '2026-09-04T00:00:00Z', from: { emailAddress: { name: 'Sender', address: 'sender@example.com' } }, subject: 'Subject', isRead: false, importance: 'high', body: { content: '<script>evil()</script><style>x{}</style><b>Body &amp; more</b>' } } }; return { status: 200, body: { value: [{ id: 'm-1', receivedDateTime: '2026-09-04T00:00:00Z', from: { emailAddress: { name: 'Sender', address: 'sender@example.com' } }, subject: 'Subject', isRead: false, importance: 'high', bodyPreview: '<b>Preview</b>', headers: 'secret', webUrl: 'https://teams.microsoft.com/l/chat/0/0' }] } }; } };
  const tools = createMicrosoftGraphTools({ enabled: true, credentialSource: { getAccessToken: async () => 'synthetic-token' }, transport });
  const listed = value(await tools['mail.list_messages'].execute(call('mail.list_messages', { folder: 'inbox', unread_only: true, limit: 1 }))); assert.equal(listed.messages[0].preview, 'Preview'); assert.equal(listed.messages[0].headers, undefined); assert.equal(requests[0].origin, 'https://graph.microsoft.com'); assert.equal(requests[0].path, '/v1.0/me/mailFolders/inbox/messages'); assert.equal(requests[0].query.$top, 1); assert.equal(requests[0].headers.authorization, 'Bearer synthetic-token');
  const read = value(await tools['mail.read_message'].execute(call('mail.read_message', { message_id: 'm-1', max_bytes: 32 }))); assert.equal(read.message.text, 'Body & more'); assert.equal(requests[1].path, '/v1.0/me/messages/m-1'); assert.equal(requests[1].headers.Prefer, 'outlook.body-content-type="text"'); assert.equal(requests[1].query.$select.includes('body'), true);
  const chats = value(await tools['teams.list_chats'].execute(call('teams.list_chats', { limit: 1 }))); assert.deepEqual(chats.chats, [{ id: 'm-1', topic: '', type: 'unknown', last_updated: null, participants: [] }]); assert.equal(requests[2].path, '/v1.0/me/chats'); assert.equal(requests[2].query.$select.includes('members'), false);
  const messages = value(await tools['teams.list_messages'].execute(call('teams.list_messages', { chat_id: 'chat-1', limit: 1 }))); assert.equal(requests.at(-1).path, '/v1.0/chats/chat-1/messages'); assert.deepEqual(requests.at(-1).query, { '$top': 1 }); assert.equal(messages.messages[0].web_url, 'https://teams.microsoft.com/l/chat/0/0');
});

test('Graph hostile response arrays are bounded before projection', async () => {
  let observed; const hostile = Array.from({ length: 100000 }, (_, index) => index === 0 ? { id: 'm-safe', subject: 'safe' } : { id: `m-${index}`, subject: 'discarded' }); const tools = createMicrosoftGraphTools({ enabled: true, credentialSource: { getAccessToken: async () => 'synthetic-token' }, transport: { request: async request => { observed = request; return { status: 200, body: { value: hostile } }; } } });
  const output = value(await tools['mail.list_messages'].execute(call('mail.list_messages', { limit: 1 }))); assert.equal(output.messages.length, 1); assert.equal(output.messages[0].id, 'm-safe'); assert.equal(output.truncated, true); assert.equal(observed.query.$top, 1);
});

test('Graph writes require preview, bind proposals, retain high-impact confirmation, and deduplicate retries', async () => {
  const requests = []; const transport = { request: async request => { requests.push(request); if (request.method === 'GET' && request.path.includes('/me/messages/')) return { status: 200, body: { id: 'draft-1', subject: 'Existing', body: { content: 'Existing draft' }, toRecipients: [{ emailAddress: { address: 'alice@example.com' } }], '@odata.etag': 'etag-1' } }; return request.method === 'POST' && request.path.endsWith('/messages') ? { status: 201, body: { id: 'draft-1' } } : { status: 204, body: {} }; } };
  const tools = createMicrosoftGraphTools({ enabled: true, credentialSource: { getAccessToken: async () => 'synthetic-token' }, transport });
  const createCall = call('mail.create_draft', { to: ['alice@example.com'], cc: ['bob@example.com'], subject: 'Hello', body: 'Synthetic body' }, 'call_create_draft');
  const unproposed = value(await tools['mail.create_draft'].execute(createCall)); assert.equal(unproposed.code, 'provider_permission_insufficient');
  const preview = await tools['mail.create_draft'].preview(createCall); assert.deepEqual(preview.recipients, ['alice@example.com', 'bob@example.com']); const created = value(await tools['mail.create_draft'].execute({ ...createCall, authorization: { kind: 'user_confirmation' } })); assert.equal(created.accepted, true); assert.equal(created.idempotency, 'new');
  const retried = value(await tools['mail.create_draft'].execute({ ...createCall, authorization: { kind: 'user_confirmation' } })); assert.equal(retried.idempotency, 'replayed'); assert.equal(requests.filter(request => request.path === '/v1.0/me/messages').length, 1); assert.deepEqual(requests[0].body.toRecipients, [{ emailAddress: { address: 'alice@example.com' } }]);
  const sendCall = call('mail.send_draft', { draft_id: 'draft-1' }, 'call_send_draft'); const sendPreview = await tools['mail.send_draft'].preview(sendCall); assert.match(sendPreview.proposal_revision, /^[a-f0-9]{64}$/); assert.equal(tools['mail.send_draft'].confirmationRequired(sendCall), true); const sent = value(await tools['mail.send_draft'].execute({ ...sendCall, authorization: { kind: 'user_confirmation' } })); assert.equal(sent.resource_id, 'draft-1'); assert.equal(requests.at(-1).headers['Idempotency-Key'].includes('call_send_draft'), true);
  const stale = call('mail.mark_read', { message_id: 'm-1', is_read: true }, 'call_mark'); await tools['mail.mark_read'].preview(stale); const changed = value(await tools['mail.mark_read'].execute(call('mail.mark_read', { message_id: 'm-2', is_read: true }, 'call_mark'))); assert.equal(changed.code, 'provider_permission_insufficient');
});

test('full_access is operator-scoped, revocable, and never model-selected', async () => {
  let now = 1000; const grants = new OperatorGrantStore({ now: () => now }); const grant = grants.grant({ capability: 'microsoft.graph.mail', provider: 'microsoft_graph', accountFingerprint: 'acct-1', scope: 'account', profile: 'full_access', expiresAt: 5000 });
  const provider = new MicrosoftGraphProvider({ enabled: true, credentialSource: { getAccessToken: async () => 'synthetic-token' }, transport: { request: async () => ({ status: 201, body: { id: 'draft-2' } }) }, permissionProfile: 'full_access', grantStore: grants, accountFingerprint: 'acct-1' }); const tools = createMicrosoftGraphTools(provider); const draft = call('mail.create_draft', { to: ['alice@example.com'], subject: 'x', body: 'x' }); await tools['mail.create_draft'].preview(draft); assert.equal(tools['mail.create_draft'].confirmationRequired(draft), false); const authorization = await tools['mail.create_draft'].authorize(draft); assert.equal(authorization.kind, 'operator_grant'); assert.equal(value(await tools['mail.create_draft'].execute({ ...draft, authorization })).accepted, true); grants.revoke('microsoft.graph.mail'); assert.equal(tools['mail.create_draft'].confirmationRequired(draft), true); const revoked = value(await tools['mail.create_draft'].execute({ ...draft, authorization })); assert.equal(revoked.code, 'provider_permission_revoked'); assert.equal(grant.profile, 'full_access'); now = 6000; assert.equal(grants.matches('microsoft.graph.mail', { provider: 'microsoft_graph', accountFingerprint: 'acct-1', scope: 'account' }), false);
});

test('operator grant replacement invalidates the prior generation and profile cannot widen access', async () => {
  const grants = new OperatorGrantStore(); let revoked = 0; grants.subscribe('microsoft.graph.mail', () => { revoked += 1; });
  grants.grant({ capability: 'microsoft.graph.mail', provider: 'microsoft_graph', accountFingerprint: 'acct-1', profile: 'ask_before_writes' });
  assert.equal(grants.get('microsoft.graph.mail').profile, 'ask_before_writes');
  grants.grant({ capability: 'microsoft.graph.mail', provider: 'microsoft_graph', accountFingerprint: 'acct-2', profile: 'full_access' });
  assert.equal(revoked, 1); assert.equal(grants.matches('microsoft.graph.mail', { provider: 'microsoft_graph', accountFingerprint: 'acct-2', scope: 'account' }), true);
  const provider = new MicrosoftGraphProvider({ enabled: true, credentialSource: { getAccessToken: async () => 'synthetic-token' }, transport: { request: async () => ({ status: 201, body: { id: 'draft-3' } }) }, permissionProfile: 'always_ask', grantStore: grants, accountFingerprint: 'acct-2' });
  assert.equal(provider.grantValid('microsoft.graph.mail'), false);
});

test('Graph grant revocation aborts an in-flight routine write', async () => {
  const grants = new OperatorGrantStore(); grants.grant({ capability: 'microsoft.graph.mail', provider: 'microsoft_graph', accountFingerprint: 'acct-2', profile: 'full_access' });
  const transport = { request: async request => await new Promise((resolve, reject) => { request.signal.addEventListener('abort', () => reject(Object.assign(new Error('cancelled'), { code: 'provider_cancelled' }))); }) };
  const tools = createMicrosoftGraphTools({ enabled: true, credentialSource: { getAccessToken: async () => 'synthetic-token' }, transport, permissionProfile: 'full_access', grantStore: grants, accountFingerprint: 'acct-2' }); const draft = call('mail.create_draft', { to: ['alice@example.com'], subject: 'x', body: 'x' }, 'call_revoke'); await tools['mail.create_draft'].preview(draft); const authorization = await tools['mail.create_draft'].authorize(draft); const pending = tools['mail.create_draft'].execute({ ...draft, authorization }); await new Promise(resolve => setImmediate(resolve)); grants.revoke('microsoft.graph.mail'); const revoked = value(await pending); assert.equal(revoked.code, 'provider_cancelled');
});

test('Graph transport timeout is bounded and typed', async () => {
  const tools = createMicrosoftGraphTools({ enabled: true, requestTimeoutMs: 100, credentialSource: { getAccessToken: async () => 'synthetic-token' }, transport: { request: async () => new Promise(() => {}) } });
  const started = Date.now(); const output = value(await tools['mail.list_messages'].execute(call('mail.list_messages', {}))); assert.equal(output.code, 'provider_timeout'); assert.ok(Date.now() - started < 1000);
});

test('Graph writes are at-most-once across concurrent and timeout retries', async () => {
  let dispatches = 0; const transport = { request: async request => { dispatches += 1; await new Promise((resolve, reject) => request.signal.addEventListener('abort', () => reject(Object.assign(new Error('timed out'), { code: 'ETIMEDOUT' })))); } };
  const tools = createMicrosoftGraphTools({ enabled: true, requestTimeoutMs: 100, credentialSource: { getAccessToken: async () => 'synthetic-token' }, transport }); const draft = call('mail.create_draft', { to: ['alice@example.com'], subject: 'x', body: 'x' }, 'call_once'); await tools['mail.create_draft'].preview(draft); const authorization = { kind: 'user_confirmation' }; const first = tools['mail.create_draft'].execute({ ...draft, authorization }); await new Promise(resolve => setImmediate(resolve)); const concurrent = value(await tools['mail.create_draft'].execute({ ...draft, authorization })); assert.equal(concurrent.code, 'provider_write_already_attempted'); const timedOut = value(await first); assert.equal(timedOut.code, 'provider_timeout'); const retry = value(await tools['mail.create_draft'].execute({ ...draft, authorization })); assert.equal(retry.code, 'provider_timeout'); assert.equal(retry.idempotency, 'replayed'); assert.equal(dispatches, 1);
});

test('controller advertises external parameters and distinguishes operator authorization from user confirmation', async () => {
  const grants = new OperatorGrantStore(); grants.grant({ capability: 'microsoft.graph.mail', provider: 'microsoft_graph', accountFingerprint: 'acct-controller', profile: 'full_access' }); let requests = 0; const provider = new MicrosoftGraphProvider({ enabled: true, permissionProfile: 'full_access', grantStore: grants, accountFingerprint: 'acct-controller', credentialSource: { getAccessToken: async () => 'synthetic-token' }, transport: { request: async () => { requests += 1; return { status: 201, body: { id: 'draft-controller' } }; } } }); const registry = createMicrosoftGraphTools(provider); let advertised;
  const engine = { async *generate({ tools, messages }) { advertised = tools.find(item => item.function.name === 'mail.create_draft'); if (!messages.some(item => item.role === 'tool')) { yield { kind: 'tool_call_chunk', text: JSON.stringify({ id: 'call_controller', name: 'mail.create_draft', arguments: { to: ['alice@example.com'], subject: 'x', body: 'x' } }) }; return; } yield { kind: 'text_delta', text: 'done' }; yield { kind: 'done', finish_reason: 'stop' }; } };
  const events = []; const controller = new ConversationController({ engine, toolRegistry: registry }); const output = await controller.runTurn({ sessionId: 'ses_controller', requestId: 'req_controller', message: 'draft a message', onEvent: event => events.push(event) }); assert.equal(output.state, 'COMPLETED'); assert.deepEqual(advertised.function.parameters, registry['mail.create_draft'].parameters); assert.equal(events.some(event => event.event === 'tool.confirmation_required'), false); assert.equal(events.find(event => event.event === 'tool.started').data.authorization, 'operator_grant'); assert.equal(requests, 1);
});

test('permission profiles apply confirmation floors to reads, writes, and T3 actions', () => {
  const names = ['mail.list_messages', 'mail.create_draft', 'mail.send_draft']; const expected = { always_ask: [true, true, true], ask_before_writes: [false, true, true], review_important_actions: [false, false, true], full_access: [true, true, true] };
  for (const [profile, values] of Object.entries(expected)) { const provider = new MicrosoftGraphProvider({ permissionProfile: profile }); assert.deepEqual(names.map(name => provider.confirmationRequired(name)), values); }
});

test('provider configuration is strict, secret-free, and preserves injected runtime wiring', () => {
  const config = mergeConfig({ providers: { microsoft_graph: { enabled: true, permission_profile: 'ask_before_writes', account_fingerprint: 'acct', scope: 'account' }, copilot: { enabled: true, executable: '/approved/copilot', allowlist: ['/approved/copilot'], version: '1.2.3' }, browser_actions: { enabled: true, executable: '/approved/chrome', allowlist: ['/approved/chrome'] } } }); assert.equal(config.providers.microsoft_graph.enabled, true); assert.equal(config.providers.browser_actions.enabled, true); assert.throws(() => validateConfig({ providers: { microsoft_graph: { token: 'must-not-be-configured' } } }), /unknown key/); assert.throws(() => validateConfig({ providers: { browser_actions: { token: 'must-not-be-configured' } } }), /unknown key/); assert.throws(() => validateConfig({ providers: { unknown: {} } }), /unknown key/); assert.throws(() => validateConfig({ providers: { copilot: { enabled: true, executable: 'copilot', allowlist: ['copilot'], version: 'latest' } } }), /executable invalid/); assert.throws(() => validateConfig({ providers: { copilot: { version: '1.2' } } }), /version invalid/); const registry = createExternalToolRegistry({ config: config.providers }); assert.equal(registry['mail.list_messages'].execute !== undefined, true); assert.equal(registry['mail.list_messages'].parameters.additionalProperties, false); assert.equal(registry.providerStatus().copilot, 'ready'); const injectedSpawn = createExternalToolRegistry({ config: config.providers, copilot: { spawn: () => new FakeChild() } }); assert.equal(injectedSpawn.providerStatus().copilot, 'unconfigured');
});

test('registry maps protected config keys explicitly and exposes provider state separately', async () => {
  assert.deepEqual(createExternalToolRegistry().providerStatus(), { microsoft_graph: 'disabled', copilot: 'disabled', browser_actions: 'disabled' }); const unconfigured = createExternalToolRegistry({ config: { microsoft_graph: { enabled: true, permission_profile: 'full_access', account_fingerprint: 'acct-config', scope: 'mailbox-1' }, browser_actions: { enabled: true } } }); assert.deepEqual(unconfigured.providerStatus(), { microsoft_graph: 'unconfigured', copilot: 'disabled', browser_actions: 'unconfigured' }); assert.throws(() => createExternalToolRegistry({ graph: { token: 'not-an-option' } }), /unknown option/);
  const grants = new OperatorGrantStore(); grants.grant({ capability: 'microsoft.graph.mail', provider: 'microsoft_graph', accountFingerprint: 'acct-config', scope: 'mailbox-1', profile: 'full_access' }); let tokenReads = 0; const registry = createExternalToolRegistry({ config: { microsoft_graph: { enabled: true, permission_profile: 'full_access', account_fingerprint: 'acct-config', scope: 'mailbox-1' } }, graph: { credentialSource: { getAccessToken: async () => { tokenReads += 1; return 'synthetic-token'; } }, transport: { request: async () => ({ status: 201, body: { id: 'draft-config' } }) }, grantStore: grants } }); assert.deepEqual(registry.providerStatus(), { microsoft_graph: 'ready', copilot: 'disabled', browser_actions: 'disabled' }); assert.equal(tokenReads, 0); const configured = createExternalToolRegistry({ config: { browser_actions: { enabled: true, executable: '/approved/chrome', allowlist: ['/approved/chrome'] } } }); assert.equal(configured.providerStatus().browser_actions, 'unverified'); const draft = call('mail.create_draft', { to: ['alice@example.com'], subject: 'x', body: 'x' }, 'call_config'); await registry['mail.create_draft'].preview(draft); assert.equal((await registry['mail.create_draft'].authorize(draft)).kind, 'operator_grant');
});

test('browser action provider uses isolated CDP sessions and binds inspected links', async () => {
  const directory = await mkdtemp(join(tmpdir(), 'lae-browser-')); let launched; let killed = false; let proxyClosed = false; const pages = new Map([['https://example.com/', { url: 'https://example.com/', title: 'Start', links: [{ href: 'https://safe.example/next', label: 'Next' }, { href: 'http://127.0.0.1/private', label: 'Private' }] }], ['https://safe.example/next', { url: 'https://safe.example/next', title: 'Next', links: [] }]]); let current = 'https://example.com/'; const cdp = { async connect() {}, async navigate(url) { current = url.href; }, async inspect() { return pages.get(current) ?? { url: current, title: '', links: [] }; }, close() {} }; const provider = new BrowserActionProvider({ enabled: true, executable: '/approved/chrome', allowlist: ['/approved/chrome'], mkdtempImpl: async () => directory, spawn: (...args) => { launched = args; const child = new EventEmitter(); child.kill = () => { killed = true; }; return child; }, proxyFactory: async () => ({ port: 43123, close: async () => { proxyClosed = true; } }), waitDevtoolsPortImpl: async () => ({ port: 43124 }), resolve: async host => host === '127.0.0.1' ? ['127.0.0.1'] : ['93.184.216.34'], cdpFactory: async () => cdp }); const tools = createBrowserActionTools(provider);
  const start = call('browser.session_start', { url: 'https://example.com/' }, 'browser_start'); assert.deepEqual(await tools['browser.session_start'].preview(start), { provider: 'browser_actions', action: 'session_start', destination: 'https://example.com/', data_egress: 'external_destination' }); const started = value(await tools['browser.session_start'].execute({ ...start, authorization: { kind: 'user_confirmation' } })); assert.equal(started.state, 'ready'); assert.equal(launched[0], '/approved/chrome'); assert.ok(launched[1].some(arg => arg.startsWith('--user-data-dir='))); assert.ok(launched[1].includes('--remote-debugging-address=127.0.0.1')); assert.ok(launched[1].includes('--remote-debugging-port=0')); assert.ok(launched[1].some(arg => arg.startsWith('--proxy-server=http://127.0.0.1:'))); const sessionId = started.browser_session_id;
  const inspected = value(await tools['browser.inspect_links'].execute(call('browser.inspect_links', { browser_session_id: sessionId, limit: 50 }, 'browser_inspect'))); assert.equal(inspected.links.length, 1); assert.equal(inspected.links[0].label, 'Next'); const follow = call('browser.follow_link', { browser_session_id: sessionId, page_revision: inspected.page_revision, link_id: inspected.links[0].id }, 'browser_follow'); const followPreview = await tools['browser.follow_link'].preview(follow); assert.equal(followPreview.destination, 'https://safe.example/next'); const followed = value(await tools['browser.follow_link'].execute({ ...follow, authorization: { kind: 'user_confirmation' } })); assert.equal(followed.url, 'https://safe.example/next'); const stale = value(await tools['browser.follow_link'].execute({ ...follow, authorization: { kind: 'user_confirmation' } })); assert.equal(stale.code, 'provider_permission_insufficient'); const closed = value(await tools['browser.session_close'].execute(call('browser.session_close', { browser_session_id: sessionId }, 'browser_close'))); assert.equal(closed.closed, true); assert.equal(killed, true); assert.equal(proxyClosed, true);
});

test('browser action provider rejects private DNS, malformed arguments, and timeout with cleanup', async () => {
  let spawned = 0; const provider = new BrowserActionProvider({ enabled: true, executable: '/approved/chrome', allowlist: ['/approved/chrome'], resolve: async () => ['::1'], spawn: () => { spawned += 1; return new EventEmitter(); }, mkdtempImpl: async () => join(tmpdir(), 'lae-browser-rejected'), rmImpl: async () => {} }); const tools = createBrowserActionTools(provider); await assert.rejects(() => tools['browser.session_start'].preview(call('browser.session_start', { url: 'https://private.example/' })), error => error.code === 'provider_destination_rejected'); assert.equal(spawned, 0); await assert.rejects(() => tools['browser.inspect_links'].execute(call('browser.inspect_links', { browser_session_id: 'x', unknown: true })), error => error.code === 'invalid_tool_arguments');
  const timeoutProvider = new BrowserActionProvider({ enabled: true, executable: '/approved/chrome', allowlist: ['/approved/chrome'], resolve: async () => ['93.184.216.34'], requestTimeoutMs: 100, spawn: () => { const child = new EventEmitter(); child.kill = () => {}; return child; }, mkdtempImpl: async () => join(tmpdir(), 'lae-browser-timeout'), rmImpl: async () => {}, proxyFactory: async () => ({ port: 43125, close: async () => {} }), waitDevtoolsPortImpl: async () => ({ port: 43126 }), cdpFactory: async () => ({ connect: async () => new Promise(() => {}), close() {} }) }); const timeoutTools = createBrowserActionTools(timeoutProvider); const timeoutCall = call('browser.session_start', { url: 'https://example.com/' }, 'browser_timeout'); await timeoutTools['browser.session_start'].preview(timeoutCall); const timedOut = value(await timeoutTools['browser.session_start'].execute({ ...timeoutCall, authorization: { kind: 'user_confirmation' } })); assert.equal(timedOut.code, 'provider_timeout'); const controller = new AbortController(); const cancelCall = call('browser.session_start', { url: 'https://example.com/' }, 'browser_cancel'); await timeoutTools['browser.session_start'].preview(cancelCall); const pending = timeoutTools['browser.session_start'].execute({ ...cancelCall, signal: controller.signal, authorization: { kind: 'user_confirmation' } }); setTimeout(() => controller.abort(), 10); assert.equal((value(await pending)).code, 'provider_cancelled');
});

test('browser URL resolution returns one validated address and bounds CDP payloads', async () => {
  const calls = []; assert.equal(await publicAddress('safe.example', async host => { calls.push(host); return ['93.184.216.34']; }), '93.184.216.34'); assert.deepEqual(calls, ['safe.example']); await assert.rejects(() => publicAddress('safe.example', async () => ['93.184.216.34', '10.0.0.1']), error => error.code === 'provider_destination_rejected');
  const client = new CdpClient({ port: 43123, WebSocketImpl: function FakeWebSocket() {}, fetchImpl: async () => ({ ok: true, headers: { get: () => '70000' }, text: async () => 'x' }) }); await assert.rejects(() => client.connect(), error => error.code === 'provider_response_too_large'); const chunkClient = new CdpClient({ port: 43123, WebSocketImpl: function FakeWebSocket() {}, fetchImpl: async () => ({ ok: true, headers: { get: () => null }, body: { getReader: () => ({ read: async () => ({ value: new Uint8Array(65537), done: false }), cancel: async () => {}, releaseLock: () => {} }) } }) }); await assert.rejects(() => chunkClient.connect(), error => error.code === 'provider_response_too_large'); let closed = false; client.socket = { close: () => { closed = true; } }; client.onMessage('x'.repeat(262145)); assert.equal(closed, true);
});

test('browser child exit closes the owned session and temporary proxy', async () => {
  const directory = await mkdtemp(join(tmpdir(), 'lae-browser-')); let child; let removed = false; let proxyClosed = false; const cdp = { async connect() {}, async navigate() {}, async inspect() { return { url: 'https://example.com/', title: '', links: [] }; }, close() {} }; const provider = new BrowserActionProvider({ enabled: true, executable: '/approved/chrome', allowlist: ['/approved/chrome'], mkdtempImpl: async () => directory, rmImpl: async () => { removed = true; }, spawn: () => { child = new EventEmitter(); child.kill = () => {}; return child; }, proxyFactory: async () => ({ port: 43123, close: async () => { proxyClosed = true; } }), waitDevtoolsPortImpl: async () => ({ port: 43124 }), resolve: async () => ['93.184.216.34'], cdpFactory: async () => cdp }); const tools = createBrowserActionTools(provider); const start = call('browser.session_start', { url: 'https://example.com/' }, 'browser_exit'); await tools['browser.session_start'].preview(start); const started = value(await tools['browser.session_start'].execute({ ...start, authorization: { kind: 'user_confirmation' } })); child.emit('exit', 1); await new Promise(resolve => setImmediate(resolve)); const stale = value(await tools['browser.inspect_links'].execute(call('browser.inspect_links', { browser_session_id: started.browser_session_id }, 'browser_exit_inspect'))); assert.equal(stale.code, 'browser_session_stale'); assert.equal(removed, true); assert.equal(proxyClosed, true);
});

test('browser action startup rejects an unsafe redirect before recording a session', async () => {
  const directory = await mkdtemp(join(tmpdir(), 'lae-browser-')); let killed = false; let removed = false; const child = new EventEmitter(); child.kill = () => { killed = true; }; const provider = new BrowserActionProvider({ enabled: true, executable: '/approved/chrome', allowlist: ['/approved/chrome'], mkdtempImpl: async () => directory, rmImpl: async () => { removed = true; }, spawn: () => child, proxyFactory: async () => ({ port: 43123, close: async () => {} }), waitDevtoolsPortImpl: async () => ({ port: 43124 }), resolve: async host => host === 'private.example' ? ['192.168.1.1'] : ['93.184.216.34'], cdpFactory: async () => ({ async connect() {}, async navigate() {}, async inspect() { return { url: 'https://private.example/', title: '', links: [] }; }, close() {} }) }); const tools = createBrowserActionTools(provider); const start = call('browser.session_start', { url: 'https://example.com/' }, 'browser_redirect'); await tools['browser.session_start'].preview(start); const rejected = value(await tools['browser.session_start'].execute({ ...start, authorization: { kind: 'user_confirmation' } })); assert.equal(rejected.code, 'provider_destination_rejected'); assert.equal(killed, true); assert.equal(removed, true);
});

class FakeChild extends EventEmitter {
  constructor({ finish = true } = {}) { super(); this.stdout = new EventEmitter(); this.stderr = new EventEmitter(); this.input = ''; this.finish = finish; this.stdin = { end: (text) => { this.input = text; if (this.finish) queueMicrotask(() => { this.stdout.emit('data', Buffer.from('copilot response')); this.emit('close', 0); }); } }; }
  kill() { this.emit('close', null); }
}

test('Copilot bridge uses stdin/minimal environment and exposes explicit cloud-egress preview', async () => {
  const children = []; const provider = new CopilotCliProvider({ enabled: true, executable: '/approved/copilot', allowlist: ['/approved/copilot'], version: '1.2.3', versionCheck: async () => true, environment: { PATH: '/approved', SECRET_TOKEN: 'must-not-pass' }, readContext: Object.assign(async () => 'const x = 1;', { estimate: async () => 12 }), spawn: (executable, args, options) => { const child = new FakeChild(); children.push({ executable, args, options, child }); return child; } }); const tool = createCopilotTool(provider); assert.equal(tool.input_schema.additionalProperties, false); const copilotCall = call('coding.copilot_ask', { prompt: 'Explain this', workspace_id: 'project', context_paths: ['src/index.js'] }, 'call_copilot'); const preview = await tool.preview(copilotCall); assert.equal(preview.destination, 'GitHub Copilot cloud'); assert.equal(preview.egress_bytes, 44); const output = value(await tool.execute({ ...copilotCall, authorization: { kind: 'user_confirmation' } })); assert.equal(output.stdout, 'copilot response'); assert.equal(output.cli_version, '1.2.3'); assert.equal(children[0].executable, '/approved/copilot'); assert.deepEqual(children[0].args, ['-s', '--no-auto-update', '--no-color', '--no-custom-instructions', '--no-experimental', '--no-remote', '--no-remote-export', '--no-ask-user', '--disable-builtin-mcps', '--disallow-temp-dir', '--log-level=none', '--available-tools=']); assert.equal(children[0].options.shell, false); assert.equal(children[0].options.detached, true); assert.deepEqual(children[0].options.env, { PATH: '/approved' }); assert.match(children[0].child.input, /const x = 1/);
  await assert.rejects(() => tool.preview(call('coding.copilot_ask', { prompt: 'x', workspace_id: 'project', context_paths: ['..\\secret'] }, 'call_path')), error => error.code === 'invalid_tool_arguments');
  const disabled = createCopilotTool(); const disabledCall = call('coding.copilot_ask', { prompt: 'x', workspace_id: 'project', context_paths: [] }, 'call_disabled'); await disabled.preview(disabledCall); const failure = value(await disabled.execute({ ...disabledCall, authorization: { kind: 'user_confirmation' } })); assert.equal(failure.code, 'copilot_cli_unavailable');
});

test('Copilot cancellation does not wait for orphans', async () => {
  let killed = 0; const provider = new CopilotCliProvider({ enabled: true, executable: '/approved/copilot', allowlist: ['/approved/copilot'], versionCheck: async () => true, readContext: async () => '', killProcess: () => { killed += 1; }, spawn: () => new FakeChild({ finish: false }) }); const tool = createCopilotTool(provider); const c = new AbortController(); const request = call('coding.copilot_ask', { prompt: 'cancel', workspace_id: 'project', context_paths: [] }, 'call_cancel'); await tool.preview(request); const pending = tool.execute({ ...request, authorization: { kind: 'user_confirmation' }, signal: c.signal }); await new Promise(resolve => setImmediate(resolve)); c.abort(); const output = value(await pending); assert.equal(output.code, 'provider_cancelled'); assert.equal(killed, 1);
});

test('Copilot rejects version mismatch and never returns stderr or broad flags', async () => {
  let child; let spawnArgs; const provider = new CopilotCliProvider({ enabled: true, executable: '/approved/copilot', allowlist: ['/approved/copilot'], versionCheck: async () => true, readContext: async () => '', spawn: (executable, args) => { spawnArgs = args; child = new FakeChild(); queueMicrotask(() => { child.stderr.emit('data', Buffer.from('secret stderr')); child.stdout.emit('data', Buffer.from('answer')); child.emit('close', 0); }); return child; } }); const tool = createCopilotTool(provider); const request = call('coding.copilot_ask', { prompt: 'x', workspace_id: 'project', context_paths: [] }, 'call_redact'); await tool.preview(request); const output = value(await tool.execute({ ...request, authorization: { kind: 'user_confirmation' } })); assert.equal(output.stdout, 'answer'); assert.equal(JSON.stringify(output).includes('secret stderr'), false); assert.ok(spawnArgs.every(arg => !arg.includes('allow-all'))); assert.equal(spawnArgs.includes('--prompt'), false);
  const mismatch = createCopilotTool({ enabled: true, executable: '/approved/copilot', allowlist: ['/approved/copilot'], versionCheck: async () => false, readContext: async () => '' }); const mismatchCall = call('coding.copilot_ask', { prompt: 'x', workspace_id: 'project', context_paths: [] }, 'call_mismatch'); await mismatch.preview(mismatchCall); assert.equal(value(await mismatch.execute({ ...mismatchCall, authorization: { kind: 'user_confirmation' } })).code, 'copilot_policy_denied');
});

test('Copilot binds context at preview and decodes split UTF-8 output safely', async () => {
  let context = 'stable'; let child; const provider = new CopilotCliProvider({ enabled: true, executable: '/approved/copilot', allowlist: ['/approved/copilot'], versionCheck: async () => true, readContext: async () => context, spawn: () => { child = new FakeChild({ finish: false }); queueMicrotask(() => { child.stdout.emit('data', Buffer.from([0xf0])); child.stdout.emit('data', Buffer.from([0x9f, 0x98, 0x80])); child.emit('close', 0); }); return child; } }); const tool = createCopilotTool(provider); const request = call('coding.copilot_ask', { prompt: 'x', workspace_id: 'project', context_paths: ['src/index.js'] }, 'call_utf8'); await tool.preview(request); context = 'changed'; assert.equal(value(await tool.execute({ ...request, authorization: { kind: 'user_confirmation' } })).code, 'copilot_policy_denied');
  context = 'stable'; const next = call('coding.copilot_ask', { prompt: 'x', workspace_id: 'project', context_paths: ['src/index.js'] }, 'call_utf8_next'); await tool.preview(next); assert.equal(value(await tool.execute({ ...next, authorization: { kind: 'user_confirmation' } })).stdout, '😀');
});

test('Copilot version probe is exact, bounded, cancellable, and minimally scoped', async () => {
  const launches = [];
  const check = createCopilotVersionCheck({ expectedVersion: '1.2.3', environment: { PATH: '/safe', SystemRoot: 'C:\\Windows', SECRET_TOKEN: 'no' }, spawn: (executable, args, options) => { const child = new FakeChild({ finish: false }); child.pid = 41; launches.push({ executable, args, options, child }); queueMicrotask(() => { child.stdout.emit('data', Buffer.from('GitHub Copilot CLI v1.2.3\n')); child.exitCode = 0; child.emit('close', 0); }); return child; } });
  assert.equal(await check('C:\\Tools\\copilot.exe'), true);
  assert.deepEqual(launches[0].args, ['--no-auto-update', '--no-color', 'version']);
  assert.deepEqual(launches[0].options.env, { PATH: '/safe', SystemRoot: 'C:\\Windows' });
  assert.throws(() => createCopilotVersionCheck({ expectedVersion: 'latest' }), /exact semantic version/);
  const mismatch = createCopilotVersionCheck({ expectedVersion: '1.2.3', spawn: () => { const child = new FakeChild({ finish: false }); queueMicrotask(() => { child.stdout.emit('data', Buffer.from('10.1.2.30')); child.exitCode = 0; child.emit('close', 0); }); return child; } });
  assert.equal(await mismatch('/copilot'), false);
  const controller = new AbortController(); controller.abort(); await assert.rejects(() => check('/copilot', controller.signal), error => error.code === 'provider_cancelled');
});

test('Copilot dispatch is at-most-once across concurrent and timed-out retries', async () => {
  let launches = 0; let killed = 0;
  const provider = new CopilotCliProvider({ enabled: true, executable: '/approved/copilot', allowlist: ['/approved/copilot'], versionCheck: async () => true, readContext: async () => '', timeoutMs: 100, killProcess: async () => { killed += 1; }, spawn: () => { launches += 1; return new FakeChild({ finish: false }); } });
  const tool = createCopilotTool(provider); const request = call('coding.copilot_ask', { prompt: 'bounded', workspace_id: 'project', context_paths: [] }, 'call_once_copilot'); await tool.preview(request); const authorized = { ...request, authorization: { kind: 'user_confirmation' } }; const first = tool.execute(authorized); await new Promise(resolve => setImmediate(resolve)); const concurrent = value(await tool.execute(authorized)); assert.equal(concurrent.code, 'provider_request_already_attempted'); const timedOut = value(await first); assert.equal(timedOut.code, 'provider_timeout'); const replay = value(await tool.execute(authorized)); assert.equal(replay.code, 'provider_timeout'); assert.equal(launches, 1); assert.equal(killed, 1);
});

test('Copilot output overflow terminates the process and fails closed', async () => {
  let child; let killed = 0; const provider = new CopilotCliProvider({ enabled: true, executable: '/approved/copilot', allowlist: ['/approved/copilot'], versionCheck: async () => true, readContext: async () => '', maxOutput: 1024, killProcess: async () => { killed += 1; }, spawn: () => { child = new FakeChild({ finish: false }); queueMicrotask(() => child.stdout.emit('data', Buffer.alloc(1025, 65))); return child; } }); const tool = createCopilotTool(provider); const request = call('coding.copilot_ask', { prompt: 'x', workspace_id: 'project', context_paths: [] }, 'call_overflow'); await tool.preview(request); const output = value(await tool.execute({ ...request, authorization: { kind: 'user_confirmation' } })); assert.equal(output.code, 'provider_response_too_large'); assert.equal(killed, 1);
});

test('Copilot Windows tree termination uses fixed taskkill argv without a shell', async () => {
  const calls = []; const child = new FakeChild({ finish: false }); child.pid = 4321; child.exitCode = null; child.signalCode = null;
  await killCopilotProcessTree(child, { platform: 'win32', graceMs: 100, spawn: (executable, args, options) => { calls.push({ executable, args, options }); const killer = new FakeChild({ finish: false }); killer.exitCode = 0; queueMicrotask(() => { child.exitCode = 1; child.emit('close', 1); killer.emit('close', 0); }); return killer; } });
  assert.deepEqual(calls[0].args, ['/PID', '4321', '/T', '/F']); assert.equal(calls[0].executable, 'taskkill.exe'); assert.equal(calls[0].options.shell, false);
});

test('Copilot provider rejects unsafe lifecycle bounds', () => {
  assert.throws(() => new CopilotCliProvider({ timeoutMs: NaN }), /invalid Copilot timeout/);
  assert.throws(() => new CopilotCliProvider({ timeoutMs: 99 }), /invalid Copilot timeout/);
  assert.throws(() => new CopilotCliProvider({ maxOutput: 1023 }), /invalid Copilot output limit/);
  assert.throws(() => new CopilotCliProvider({ maxOutput: 65537 }), /invalid Copilot output limit/);
});
