#!/usr/bin/env node
import { readFile } from 'node:fs/promises';
import { FixtureEngineClient } from './host/engine/fixture-engine.mjs';
import { NativeEngineClient } from './host/engine/native-engine-client.mjs';
import { ConversationController } from './host/agent/controller.mjs';
import { ActionJournal } from './host/agent/action-journal.mjs';
import { HostServer } from './host/server/host-server.mjs';
import { mergeConfig } from './host/agent/config.mjs';
import { createLocalToolRegistry } from './host/tools/local/index.mjs';
import { createExternalToolRegistry, OperatorGrantStore, OperatorGrantControl, buildOperatorGrantBindings } from './host/providers/index.mjs';

const configPath = process.env.LAE_CONFIG_PATH;
let fileConfig = {};
if (configPath) { try { fileConfig = JSON.parse(await readFile(configPath, 'utf8')); } catch (error) { throw new Error(`config_load_failed: ${error.message}`); } }
const configuredMode = fileConfig.engine?.mode;
const envMode = process.env.LAE_ENGINE_MODE;
if (envMode && !['fixture', 'native'].includes(envMode)) throw new Error('invalid LAE_ENGINE_MODE; expected fixture or native');
if (envMode && configuredMode && envMode !== configuredMode) throw new Error('engine mode conflict between config and LAE_ENGINE_MODE');
const mode = envMode ?? configuredMode ?? 'fixture';
const endpoint = process.env.LAE_ENGINE_ENDPOINT ?? fileConfig.engine?.endpoint;
const token = process.env.LAE_ENGINE_TOKEN;
const model = process.env.LAE_ENGINE_MODEL ?? fileConfig.engine?.model;
const backend = process.env.LAE_ENGINE_BACKEND ?? fileConfig.engine?.backend;
const requestTimeoutMs = Number(process.env.LAE_ENGINE_TIMEOUT_MS ?? fileConfig.engine?.request_timeout_ms ?? 120000);
if (mode === 'fixture' && (endpoint || token)) throw new Error('native engine settings supplied while fixture mode is selected');
const config = mergeConfig({ ...fileConfig, engine: { ...(fileConfig.engine ?? {}), mode } });
if (mode === 'native' && (!model || !backend)) throw new Error('native engine model and backend must be explicit in config or environment');
const engine = mode === 'native' ? new NativeEngineClient({ endpoint, token, model, backend, timeoutMs: requestTimeoutMs }) : new FixtureEngineClient();
if (mode === 'native') await engine.waitReady();
const grantStore = new OperatorGrantStore();
const operatorGrants = new OperatorGrantControl({ store: grantStore, bindings: buildOperatorGrantBindings(config) });
const externalTools = createExternalToolRegistry({ config: config.providers, workspaceRoots: config.workspace_roots, graph: { grantStore } });
const processEnvironment = Object.fromEntries(['SystemRoot', 'WINDIR'].filter(key => typeof process.env[key] === 'string').map(key => [key, process.env[key]]));
const actionJournal = process.env.LAE_ACTION_JOURNAL_DIR ? await ActionJournal.open({ directory: process.env.LAE_ACTION_JOURNAL_DIR }) : undefined;
const localTools = createLocalToolRegistry({ workspaces: config.workspace_roots, applications: config.applications, process_actions: config.process_actions, processEnvironment, networkProvider: config.network.provider, grantControl: operatorGrants });
const localCapabilities = localTools.capabilitySnapshot;
const toolRegistry = { ...localTools, ...externalTools };
const controller = new ConversationController({ engine, actionJournal, toolRegistry });
const host = new HostServer({ controller, engine, config, providers: externalTools.providerStatus, providerAuth: externalTools.providerAuthControl, providerShutdown: externalTools.shutdown, operatorGrants, actionJournal, localCapabilities });
const address = await host.listen(Number(process.env.LAE_PORT ?? 0));
if (process.env.LAE_REVEAL_BOOTSTRAP_URL === '1') console.log(address.bootstrap_url);
else console.log(JSON.stringify({ ready: true, host: address.host, port: address.port, bootstrap: 'hidden-use-approved-launcher', engine: mode, network: config.network.provider, action_journal: actionJournal?.health().state ?? 'unavailable' }));
const shutdown = async () => { await host.close(); process.exit(0); };
process.once('SIGINT', shutdown); process.once('SIGTERM', shutdown);
