const token = document.querySelector('meta[name="lae-token"]').content;
const headers = { authorization: `Bearer ${token}`, 'content-type': 'application/json' };
const transcript = document.querySelector('#transcript');
const status = document.querySelector('#status');
let sessionId;
let mode = 'normal';
let activeRequest;
const previews = new Map();

const add = (text, cls) => {
  const el = document.createElement('div'); el.className = `message ${cls}`; el.textContent = text; transcript.append(el); transcript.scrollTop = transcript.scrollHeight; return el;
};
function detail(card, label, value) { const row = document.createElement('div'); row.className = 'confirmation-detail'; const name = document.createElement('strong'); name.textContent = `${label}: `; const text = document.createElement('span'); text.textContent = value; row.append(name, text); card.append(row); }
function renderConfirmation(ev) {
  const call = ev.data?.call ?? {}; const preview = ev.data?.preview ?? previews.get(call.id) ?? {}; const card = document.createElement('div'); card.className = 'event-card confirmation-card'; const heading = document.createElement('strong'); heading.textContent = `Confirmation required for ${typeof call.name === 'string' ? call.name : 'tool action'}`; card.append(heading);
  if (ev.data?.phase === 'preview_access') { detail(card, 'Purpose', 'Read the existing draft to prepare a send preview'); detail(card, 'Destination', 'Signed-in Outlook mailbox'); }
  else if (call.name === 'mail.create_draft' || call.name === 'mail.send_draft') { if (typeof preview.draft_id === 'string') detail(card, 'Draft', preview.draft_id); if (Array.isArray(preview.recipients)) detail(card, 'Recipients', preview.recipients.join(', ')); if (typeof preview.subject === 'string') detail(card, 'Subject', preview.subject); if (typeof preview.body_preview === 'string') detail(card, 'Body preview', preview.body_preview + (preview.body_truncated ? '…' : '')); }
  else if (call.name === 'teams.send_message') { if (typeof preview.chat_id === 'string') detail(card, 'Chat', preview.chat_id); if (typeof preview.body_preview === 'string') detail(card, 'Message preview', preview.body_preview); }
  else if (typeof preview.destination === 'string') detail(card, 'External destination (network egress)', preview.destination); else detail(card, 'Effect', 'This action may cause an external side effect.');
  if (typeof preview.data_categories?.join === 'function') detail(card, 'Data', preview.data_categories.join(', '));
  const actions = document.createElement('div'); actions.className = 'confirmation-actions'; const submit = approved => { for (const button of actions.querySelectorAll('button')) button.disabled = true; return fetch(`/api/tool-confirmations/${ev.data.confirmation_id}`, { method: 'POST', headers, body: JSON.stringify({approved,request_id:ev.request_id,call_id:call.id}) }); };
  const approve = document.createElement('button'); approve.type = 'button'; approve.textContent = 'Approve'; approve.onclick = () => { void submit(true); }; const deny = document.createElement('button'); deny.type = 'button'; deny.textContent = 'Deny'; deny.onclick = () => { void submit(false); }; actions.append(approve, deny); card.append(actions); transcript.append(card); transcript.scrollTop = transcript.scrollHeight;
}
async function renderGrants() { const response = await fetch('/api/operator-grants', { headers }); if (!response.ok) return; const { capabilities = [] } = await response.json(); const list = document.querySelector('#grant-list'); list.replaceChildren(); if (!capabilities.length) { const empty = document.createElement('p'); empty.textContent = 'No grantable capabilities are configured.'; list.append(empty); return; } for (const item of capabilities) { const row = document.createElement('div'); row.className = 'grant-row'; const description = document.createElement('span'); description.textContent = item.label; const detailText = document.createElement('small'); detailText.textContent = `${item.provider} · ${item.scope}${item.granted ? ` · expires ${new Date(item.expires_at).toLocaleTimeString()}` : ''}`; description.append(detailText); const button = document.createElement('button'); button.type = 'button'; button.textContent = item.granted ? 'Revoke' : 'Grant 1 hour'; button.onclick = async () => { if (!item.granted && !confirm(`Grant one hour of full access to: ${item.label}?\n\nThis does not auto-approve external sends, installs, elevation, purchases, deletion, or security changes.`)) return; const body = item.granted ? { granted: false } : { granted: true, duration_ms: 3600000 }; await fetch(`/api/operator-grants/${item.capability}`, { method: 'POST', headers, body: JSON.stringify(body) }); await renderGrants(); }; row.append(description, button); list.append(row); } }
async function init() { const response = await fetch('/api/sessions', { method: 'POST', headers, body: '{}' }); const data = await response.json(); sessionId = data.session_id; const runtime = await fetch('/api/status', { headers }); const info = await runtime.json(); document.querySelector('#engine').textContent = info.engine.engine ?? 'fixture'; document.querySelector('#backend').textContent = info.engine.backend ?? 'unknown'; document.querySelector('#network').textContent = info.network.provider; await renderGrants(); status.textContent = 'Ready — loopback only'; }
async function send(event) { event.preventDefault(); const input = document.querySelector('#message'); const message = input.value.trim(); if (!message || activeRequest) return; input.value = ''; add(message, 'user'); const requestId = `req_${crypto.randomUUID().replaceAll('-', '')}`; activeRequest = requestId; const out = add('', 'assistant'); const response = await fetch('/api/chat', { method: 'POST', headers, body: JSON.stringify({ session_id: sessionId, message, mode, request_id: requestId }) }); if (!response.ok) { out.textContent = `Request failed (${response.status})`; activeRequest = null; previews.clear(); return; } const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ''; for (;;) { const { value, done } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const frames = buffer.split('\n\n'); buffer = frames.pop(); for (const frame of frames) { const line = frame.split('\n').find(value => value.startsWith('data: ')); if (!line) continue; try { const ev = JSON.parse(line.slice(6)); if (ev.event === 'message.delta') out.textContent += ev.data.text; else if (ev.event === 'tool.proposed' && ev.data.call?.id) { const destination = ev.data.preview?.destination; if (typeof destination === 'string') previews.set(ev.data.call.id,destination); previews.set(ev.data.call.id, ev.data.preview ?? {}); } else if (ev.event === 'tool.confirmation_required') renderConfirmation(ev); else if (ev.event === 'request.failed' || ev.event === 'request.cancelled') out.textContent += `\n[${ev.data.code}]`; } catch { /* malformed UI event is ignored */ } } } activeRequest = null; previews.clear(); }
document.querySelector('#chat').addEventListener('submit', send); document.querySelector('#stop').onclick = () => { if (activeRequest) void fetch('/api/cancel', { method: 'POST', headers, body: JSON.stringify({ request_id: activeRequest }) }); }; document.querySelector('#reset').onclick = () => { if (sessionId) void fetch('/api/sessions', { method: 'POST', headers, body: JSON.stringify({ session_id: sessionId, reset: true }) }); transcript.replaceChildren(); }; document.querySelector('#normal').onclick = () => { mode = 'normal'; document.querySelector('#normal').setAttribute('aria-pressed', 'true'); document.querySelector('#deep').setAttribute('aria-pressed', 'false'); }; document.querySelector('#deep').onclick = () => { mode = 'deep'; document.querySelector('#deep').setAttribute('aria-pressed', 'true'); document.querySelector('#normal').setAttribute('aria-pressed', 'false'); }; init().catch(() => { status.textContent = 'Host unavailable'; });
async function refreshGraphAuth() { const response = await fetch('/api/provider-auth/microsoft_graph', { headers }); if (!response.ok) return; const auth = (await response.json()).microsoft_graph ?? {}; const label = document.querySelector('#graph-auth-status'); label.textContent = auth.prompt ? `Enter ${auth.prompt.userCode} at ${auth.prompt.verificationUri}` : auth.state === 'authenticated' ? `Connected (${typeof auth.accountFingerprint === 'string' ? auth.accountFingerprint.slice(0, 12) : 'account verified'}…)` : auth.state; }
async function startGraphAuth() { const response = await fetch('/api/provider-auth/microsoft_graph/start', { method: 'POST', headers, body: '{}' }); if (!response.ok) return; for (let count = 0; count < 900; count += 1) { await refreshGraphAuth(); const statusResponse = await fetch('/api/provider-auth/microsoft_graph', { headers }); const state = (await statusResponse.json()).microsoft_graph?.state; if (state !== 'requesting_device_code' && state !== 'awaiting_user') break; await new Promise(resolve => setTimeout(resolve, 1000)); } }
document.querySelector('#revoke-all').onclick = async () => { if (activeRequest) await fetch('/api/cancel', { method: 'POST', headers, body: JSON.stringify({ request_id: activeRequest }) }); await fetch('/api/operator-grants/revoke-all', { method: 'POST', headers, body: '{}' }); await renderGrants(); }; document.querySelector('#graph-auth').onclick = () => { void startGraphAuth().catch(() => { document.querySelector('#graph-auth-status').textContent = 'Authentication failed'; }); }; document.querySelector('#graph-auth-cancel').onclick = async () => { await fetch('/api/provider-auth/microsoft_graph/cancel', { method: 'POST', headers, body: '{}' }); await refreshGraphAuth(); }; document.querySelector('#graph-auth-clear').onclick = async () => { await fetch('/api/provider-auth/microsoft_graph/clear', { method: 'POST', headers, body: '{}' }); await refreshGraphAuth(); }; refreshGraphAuth().catch(() => {});
